import { createContext, useContext, useEffect, useState } from "react"

export type Language = "en" | "fr" | "mc"

type Translations = {
    [key in Language]: {
        [key: string]: string
    }
}

const translations: Translations = {
    en: {
        "app.title": "EduTrack",
        "nav.myCourses": "My Courses",
        "nav.noCourses": "No courses yet.",
        "nav.newCourse": "New Course",
        "nav.settings": "Settings",
        "nav.selectProfile": "Please select a profile first.",
        "course.create.title": "Create New Course",
        "course.create.name": "Course Title",
        "course.create.desc": "Description (Optional)",
        "course.create.color": "Color Tag",
        "course.create.cancel": "Cancel",
        "course.create.submit": "Create Course",
        "course.create.loading": "Creating...",
        "course.delete.confirm": "Are you sure you want to delete this course? All items will be lost.",
        "item.delete.confirm": "Are you sure you want to delete this item?",
        "course.notFound": "Course not found or loading...",
        "course.addContent": "Add Content",
        "course.tabs.all": "All Content",
        "course.tabs.exercises": "Exercises",
        "course.tabs.notes": "Notes",
        "course.tabs.resources": "Resources",
        "course.empty": "No items found in this section.",
        "course.search": "Search items...",
        "item.create.title": "Add Content",
        "item.create.type.note": "Note",
        "item.create.type.exercise": "Exercise",
        "item.create.type.resource": "Resource",
        "item.form.title": "Title",
        "item.form.title.placeholder.note": "e.g. Lecture Summary",
        "item.form.title.placeholder.exercise": "e.g. Calculus Drill 1",
        "item.form.title.placeholder.resource": "e.g. Textbook PDF",
        "item.form.content": "Content",
        "item.form.status": "Status",
        "item.form.difficulty": "Difficulty",
        "item.form.desc": "Description",
        "item.form.file": "File",
        "item.form.file.placeholder": "Click or drag file here",
        "item.form.file.supports": "Supports PDF, Images, ZIP",
        "item.form.submit.note": "Create Note",
        "item.form.submit.exercise": "Create Exercise",
        "item.form.submit.resource": "Create Resource",
        "item.noContent": "No content to display.",
        "status.todo": "To Do",
        "status.in-progress": "In Progress",
        "status.completed": "Completed",
        "diff.easy": "Easy",
        "diff.medium": "Medium",
        "diff.hard": "Hard",
        "theme.toggle": "Toggle theme",
        "lang.toggle": "Language", // Generic label for dropdown
        "welcome.empty.title": "Start your Learning Journey",
        "welcome.empty.desc": "Create your first course to begin tracking your progress.",
        "welcome.create.button": "Create First Course",
        "welcome.title": "Welcome back!",
        "welcome.subtitle": "Select a course to start learning or manage your content.",
        "welcome.card.title": "Getting Started",
        "welcome.card.desc": "Create your first course using the sidebar.",
        "profiles.manager.title": "Manage Profiles",
        "profiles.dropdown.select": "Select Profile",
        "profiles.dropdown.switch": "Switch Profile",
        "profiles.dropdown.add": "Add Profile",
        "profiles.dropdown.manage": "Manage Profiles",
        "profiles.dropdown.logout": "Logout (Close Profile)",
        "dashboard.stats.courses": "Courses",
        "dashboard.stats.exercises": "Exercises",
        "dashboard.stats.notes": "Notes",
        "dashboard.recent": "Recent Courses",
        "dashboard.inprogress": "In Progress",
        "dashboard.activity": "Activity Log",
        "dashboard.empty.courses": "No courses yet.",
        "dashboard.empty.activity": "No recent activity.",
        "changelog.title": "What's New",
        "changelog.view": "View Changelog",
        "changelog.desc": "View the update history.",
        "drop.title": "Drop file to upload",
        "folder.new": "New Subject",
        "folder.create.sub": "New Sub-Folder",
        "folder.create.prompt": "Enter folder name:",
        "folder.delete.confirm": "Delete this folder? Content will move to parent.",
        "settings.title": "Course Settings",
        "action.delete": "Delete",
        "action.cancel": "Cancel",
        // Search
        "search.placeholder": "Search courses, notes, exercises...",
        "search.noResults": "No results found for",
        "search.type": "Type to search...",
        "search.searching": "Searching...",
        "search.results": "results",
        "search.nav": "to navigate",
        "search.select": "to select",
        // Summary
        "summary.title": "Summarization Options",
        "summary.compression": "Compression",
        "summary.format": "Format",
        "summary.preserveHeadings": "Preserve Headings",
        "summary.detectKeywords": "Detect Keywords (Formulas, Dates)",
        "summary.useWebSearch": "Active Web Research (Perplexity)",
        "summary.desc.20": "Ultra-short. Definitions & key formulas only.",
        "summary.desc.40": "Balanced. Recommended for general study.",
        "summary.desc.50": "Detailed. Includes examples and context.",
        "summary.generate": "Generate Summary",
        "summary.generated": "Generated Summary",
        "summary.copy": "Copy to clipboard",
        "summary.regenerate": "Regenerate",
        "summary.configure": "Configure",
        "summary.view": "View Summary",
        "summary.hide": "Hide Summary",
        "summary.trigger": "Summarize",
        "summary.stats.words": "Words",
        "summary.stats.ratio": "Ratio",
        "summary.stats.time": "Time",
        "summary.error.noContent": "No text content found to summarize. PDF/Image content is not currently supported.",
        "summary.fmt.bullets": "Bullets",
        "summary.fmt.paragraph": "Paragraph",
        "summary.fmt.outline": "Outline",
        "summary.fmt.timeline": "Timeline",
        "summary.provider": "Generator Model",
        "summary.error.ai": "AI Generation Failed. Check if API keys are valid.",
        // Common / Folder
        "common.folder": "Folder",
        "common.noDesc": "No description",
        "folder.empty": "This folder is empty.",
        // New Additions
        "focus.enter": "Focus Mode",
        "focus.exit": "Exit Focus",
        "focus.enter.tooltip": "Enter Focus Mode",
        "focus.exit.tooltip": "Exit Focus Mode (Esc)",
        "summary.generating": "Drafting academic summary...",
        "summary.error.display": "Error displaying summary.",
        "file.unknownSize": "Unknown size",
        "file.attached": "Attached File",
        "file.download": "Download",
        "course.return": "Back to Course",
        "export.defaultTitle": "Summary",
        "export.generatedOn": "Generated on:",
        "export.contentComplex": "Complex content",
        "bulk.selected_singular": "Item selected",
        "bulk.selected_plural": "Items selected",
        "common.delete": "Delete",
        "common.cancel": "Cancel",
        // Settings Page
        "settings.page.title": "Settings",
        "settings.page.subtitle": "Manage your global preferences and configurations.",
        "settings.tabs.api": "API Keys & Services",
        "settings.tabs.appearance": "Appearance",
        "settings.tabs.shortcuts": "Keyboard Shortcuts",
        "settings.api.title": "Service Configuration",
        "settings.api.desc": "Configure API keys for AI services and integrations.",
        "settings.appearance.title": "Appearance",
        "settings.appearance.desc": "Customize the application look and feel.",
        "settings.shortcuts.title": "Keyboard Shortcuts",
        "settings.shortcuts.desc": "Master the app with quick commands.",
        "settings.shortcuts.global": "Global Navigation",
        "settings.shortcuts.flashcards": "Flashcards",
        "settings.theme.light": "Light",
        "settings.theme.dark": "Dark",
        "settings.theme.system": "System",

        'sort.by': 'Sort by',
        'sort.label': 'Sort by',
        'sort.alpha': 'Alphabetical',
        'sort.date': 'Date added',
        'sort.dateAdded': 'Date added',
        'sort.last_opened': 'Last opened',
        'sort.lastOpened': 'Last opened',
        'view.grid': 'Grid',
        'view.list': 'List',
        'action.selectAll': 'Select All',
        'grid.columns': 'Columns',
        "settings.save.button": "Save Keys",
        "settings.save.saving": "Saving...",
        "settings.save.success": "API Keys saved successfully!",
        "settings.save.error": "Error saving keys.",
        "settings.api.perplexity.default": "Perplexity AI (Default)",
        "settings.api.perplexity.summaries": "Perplexity - Summaries",
        "settings.api.perplexity.exercises": "Perplexity - Exercises",
        "settings.api.gemini.vincent": "Google Gemini (Vincent Pena)",
        "settings.api.gemini.summaries": "Google Gemini - Summaries",
        "settings.api.gemini.exercises": "Google Gemini - Exercises",
        "settings.api.integrations": "Integrations",
        "settings.api.calendar": "Google Calendar Authorization",
        // Generation Menu
        "gen.menu.button": "AI Generation",
        "gen.menu.title": "Generate Content",
        "gen.flashcards.title": "Flashcards",
        "gen.flashcards.desc": "Memory cards for spaced repetition.",
        "gen.quiz.title": "Smart Quiz",
        "gen.quiz.desc": "Multiple choice questions to test knowledge.",
        "gen.plan.title": "Study Plan",
        "gen.plan.desc": "AI-powered weekly schedule.",
        "gen.viewAll": "View all exercises",
        "gen.empty": "No generated content",
        "gen.start": "Start items",
        "gen.list.cards": "cards",
        "gen.list.questions": "Qs",
        "gen.list.mastery": "Mastery",
        "gen.action.start": "Start",
        "gen.action.quiz": "Take Quiz",
        "gen.delete.confirm": "Do you really want to delete this exercise?",
        "gen.delete.error": "Error during deletion",
        "common.open": "Open",
        "common.in": "in",
        "changelog.v051.title": "Mobility & Stability 📱⚡",
        "changelog.v051.mobile": "Mobile Optimization: Redesigned the course view for smartphones with more compact cards and an intelligent header.",
        "changelog.v051.folders": "Fluid Navigation: Folders are now open by default for direct access to your courses.",
        "changelog.v051.office": "Hybrid Office Viewer: Transition to Google Viewer for reliable opening of PPT and Excel on all devices.",
        "changelog.v051.api": "API Interceptor: Automatic detection of expired sessions and intelligent reconnection.",
        "changelog.v051.deps": "Dependencies: Fixed compilation errors related to Word (docx-preview) and HEIC (heic2any) modules.",
        "changelog.v051.prisma": "Prisma Sync: Updated the database engine for perfect server type consistency.",
        "changelog.v050.title": "Stability & Intelligence 🧠",
        "changelog.v050.api_keys": "API Key Persistence: Critical fix for disappearing keys. They are now stored securely.",
        "changelog.v050.logout": "Clean Logout: The 'Logout' button now correctly cleans up the session and token.",
        "changelog.v050.ai_reliability": "AI Reliability: Fixed 404/500 errors during flashcard generation and better Gemini quota management.",
        "changelog.v050.polish": "Localization Polish: Fixed French translations and ensured the 'Minecraft' theme applies everywhere.",
        "changelog.v041.title": "Resource Hub 📂",
        "changelog.v041.viewer": "Multi-Format Viewer: Native support for PDF, Office docs (Word, Excel, PowerPoint) and images directly in the app.",
        "changelog.v041.metadata": "Metadata: Clearer resource cards showing format, date and full name.",
        "changelog.v041.delete_fix": "Secure Deletion: Fixed 'File not found' errors and added visual feedback.",
        "changelog.v041.doc_type": "Doc Detection: Robust file type detection ensuring opening in the correct viewer.",
        "changelog.v040.title": "Cloud Sync Overhaul 🔄",
        "changelog.v040.infra": "Sync Infrastructure: Backend synchronization entirely rebuilt to fix authentication and routing.",
        "changelog.v040.upload": "File Upload: Resolved 404 errors (Nginx).",
        "changelog.v040.schema": "Database Schema: Fixed UUID generation for folders and courses.",
        "changelog.v040.speed": "Sync Speed: Interval reduced from 30s to 3s for near-instant updates.",
        "changelog.v040.cleanup": "Smart Cleanup: Auto-deletion of old records (>7 days).",
        "changelog.v040.tombstone": "Tombstone Optimization: Deletion sync over 24h only.",
        "changelog.v040.nginx": "Nginx Config: Fixed API routing (/api/, /auth/, /sync).",
        "changelog.v030.title": "Focus & Localization 🌍",
        "changelog.v030.focus": "Focus Mode: Fullscreen summaries without distraction.",
        "changelog.v030.multilang": "Multi-Language: Available in English, French and... Minecraft?",
        "changelog.v030.ai2": "AI Summaries 2.0: Uses Gemini for more relevant summaries.",
        "changelog.v030.export": "Improved Export: Download in PDF and Word (.docx).",
        "changelog.v020.title": "PDF Export & Search",
        "changelog.v020.pdf": "PDF Export: Professional PDF generation for your summaries.",
        "changelog.v020.command": "Command Center: `Cmd+K` to search everything instantly.",
        "changelog.v020.analytics": "Analytics: Activity timeline.",
        "changelog.v020.large_files": "Optimization for large files.",
        "changelog.v015.title": "Structure & Organization",
        "changelog.v015.recursive": "Recursive Folders: Infinite tree structure.",
        "changelog.v015.favorites": "Quick Favorites: Pin your important courses.",
        "changelog.v015.dnd": "Drag & Drop: Intuitive reorganization.",
        "changelog.v010.title": "Genesis",
        "changelog.v010.engine": "Learning Engine: Courses, Notes, Exercises.",
        "changelog.v010.graph": "Knowledge Graph: Interactive visualization.",
        "changelog.current": "CURRENT"
    },
    fr: {
        "app.title": "EduTrack",
        "nav.myCourses": "Mes Cours",
        "nav.noCourses": "Aucun cours pour le moment.",
        "nav.newCourse": "Nouveau Cours",
        "nav.settings": "Paramètres",
        "nav.selectProfile": "Veuillez d'abord sélectionner un profil.",
        "course.create.title": "Créer un nouveau cours",
        "course.create.name": "Titre du cours",
        "course.create.desc": "Description (Optionnel)",
        "course.create.color": "Couleur",
        "course.create.cancel": "Annuler",
        "course.create.submit": "Créer le cours",
        "course.create.loading": "Création...",
        "course.delete.confirm": "Êtes-vous sûr de vouloir supprimer ce cours ? Tout le contenu sera perdu.",
        "item.delete.confirm": "Voulez-vous vraiment supprimer cet élément ?",
        "course.notFound": "Cours introuvable ou chargement...",
        "course.addContent": "Ajouter du contenu",
        "course.tabs.all": "Tout",
        "course.tabs.exercises": "Exercices",
        "course.tabs.notes": "Notes",
        "course.tabs.resources": "Ressources",
        "course.empty": "Aucun élément trouvé dans cette section.",
        "course.search": "Rechercher...",
        "item.create.title": "Ajouter du contenu",
        "item.create.type.note": "Note",
        "item.create.type.exercise": "Exercice",
        "item.create.type.resource": "Ressource",
        "item.form.title": "Titre",
        "item.form.title.placeholder.note": "ex: Résumé de cours",
        "item.form.title.placeholder.exercise": "ex: TD Analyse 1",
        "item.form.title.placeholder.resource": "ex: Manuel PDF",
        "item.form.content": "Contenu",
        "item.form.status": "Statut",
        "item.form.difficulty": "Difficulté",
        "item.form.desc": "Description",
        "item.form.file": "Fichier",
        "item.form.file.placeholder": "Cliquez ou glissez un fichier ici",
        "item.form.file.supports": "Supporte PDF, Images, ZIP",
        "item.form.submit.note": "Créer la Note",
        "item.form.submit.exercise": "Créer l'Exercice",
        "item.form.submit.resource": "Ajouter la Ressource",
        "item.noContent": "Aucun contenu à afficher.",
        "status.todo": "À faire",
        "status.in-progress": "En cours",
        "status.completed": "Terminé",
        "diff.easy": "Facile",
        "diff.medium": "Moyen",
        "diff.hard": "Difficile",
        "theme.toggle": "Changer de thème",
        "lang.toggle": "Langue",
        "welcome.empty.title": "Commencez votre apprentissage",
        "welcome.empty.desc": "Créez votre premier cours pour commencer à suivre vos progrès.",
        "welcome.create.button": "Créer mon premier cours",
        "welcome.title": "Bon retour !",
        "welcome.subtitle": "Sélectionnez un cours pour commencer.",
        "welcome.card.title": "Pour commencer",
        "welcome.card.desc": "Créez votre premier cours via la barre latérale.",
        "profiles.manager.title": "Gérer les Profils",
        "profiles.dropdown.select": "Sélect. Profil",
        "profiles.dropdown.switch": "Changer de Profil",
        "profiles.dropdown.add": "Ajouter un Profil",
        "profiles.dropdown.manage": "Gérer les Profils",
        "profiles.dropdown.logout": "Déconnexion (Fermer)",
        "dashboard.stats.courses": "Cours",
        "dashboard.stats.exercises": "Exercices",
        "dashboard.stats.notes": "Notes",
        "dashboard.recent": "Cours Récents",
        "dashboard.inprogress": "En Cours",
        "dashboard.activity": "Journal d'Activité",
        "dashboard.empty.courses": "Aucun cours pour l'instant.",
        "dashboard.empty.activity": "Aucune activité récente.",
        "changelog.title": "Nouveautés",
        "changelog.view": "Voir les changements",
        "changelog.desc": "Consultez l'historique des mises à jour.",
        "drop.title": "Lâchez le fichier pour uploader",
        "folder.new": "Nouveau Sujet",
        "folder.create.sub": "Nouveau Sous-Dossier",
        "folder.create.prompt": "Entrez le nom du dossier :",
        "folder.delete.confirm": "Supprimer ce dossier ? Le contenu remontera au parent.",
        "settings.title": "Paramètres du Cours",
        "action.delete": "Supprimer",
        "action.cancel": "Annuler",
        // Search
        "search.placeholder": "Chercher cours, notes, exercices...",
        "search.noResults": "Aucun résultat pour",
        "search.type": "Tapez pour chercher...",
        "search.searching": "Recherche en cours...",
        "search.results": "résultats",
        "search.nav": "naviguer",
        "search.select": "sélectionner",
        // Summary
        "summary.title": "Options de Résumé",
        "summary.compression": "Compression",
        "summary.format": "Format",
        "summary.preserveHeadings": "Garder les titres",
        "summary.detectKeywords": "Détecter Mots-clés (Dates, Formules)",
        "summary.useWebSearch": "Recherche Web Contextuelle (Perplexity)",
        "summary.desc.20": "Ultra-court. Définitions & formules clés seulement.",
        "summary.desc.40": "Équilibré. Recommandé pour l'étude.",
        "summary.desc.50": "Détaillé. Inclut exemples et contexte.",
        "summary.generate": "Générer Résumé",
        "summary.generated": "Résumé Généré",
        "summary.copy": "Copier",
        "summary.regenerate": "Régénérer",
        "summary.configure": "Configurer",
        "summary.view": "Voir Résumé",
        "summary.hide": "Masquer Résumé",
        "summary.trigger": "Résumer",
        "summary.stats.words": "Mots",
        "summary.stats.ratio": "Ratio",
        "summary.stats.time": "Temps",
        "summary.error.noContent": "Aucun contenu texte trouvé pour le résumé. Les fichiers PDF/Images ne sont pas encore supportés.",
        "summary.fmt.bullets": "Puces",
        "summary.fmt.paragraph": "Paragraphe",
        "summary.fmt.outline": "Plan",
        "summary.fmt.timeline": "Chronologie",
        "summary.provider": "Modèle de Génération",
        "summary.error.ai": "Échec de l'IA. Vérifiez vos clés d'API.",
        // Common / Folder
        "common.folder": "Dossier",
        "common.noDesc": "Aucune description",
        "folder.empty": "Ce dossier est vide.",
        // New Additions
        "focus.enter": "Mode Concentration",
        "focus.exit": "Quitter Focus",
        "focus.enter.tooltip": "Entrer en Mode Concentration",
        "focus.exit.tooltip": "Quitter le mode concentration (Echap)",
        "summary.generating": "Rédaction du résumé académique en cours...",
        "summary.error.display": "Erreur d'affichage du résumé.",
        "file.unknownSize": "Taille inconnue",
        "file.attached": "Fichier Joint",
        "file.download": "Télécharger",
        "course.return": "Retour au Cours",
        "export.defaultTitle": "Résumé",
        "export.generatedOn": "Généré le :",
        "export.contentComplex": "Contenu complexe",
        "bulk.selected_singular": "Élément sélectionné",
        "bulk.selected_plural": "Éléments sélectionnés",
        "common.delete": "Supprimer", // Added because BulkBar uses it
        "common.cancel": "Annuler",
        // Settings Page
        "settings.page.title": "Paramètres",
        "settings.page.subtitle": "Gérez vos préférences et configurations globales.",
        "settings.tabs.api": "Clés API & Services",
        "settings.tabs.appearance": "Apparence",
        "settings.tabs.shortcuts": "Raccourcis Clavier",
        "settings.api.title": "Configuration des Services",
        "settings.api.desc": "Configurez vos clés d'API pour les services d'IA et les intégrations.",
        "settings.appearance.title": "Apparence",
        "settings.appearance.desc": "Personnalisez le look de votre application.",
        "settings.shortcuts.title": "Raccourcis Clavier",
        "settings.shortcuts.desc": "Maîtrisez l'application avec les commandes rapides.",
        "settings.shortcuts.global": "Navigation Globale",
        "settings.shortcuts.flashcards": "Flashcards",
        "settings.theme.light": "Clair",
        "settings.theme.dark": "Sombre",
        "settings.theme.system": "Système",

        // Trier & Vue
        'sort.by': 'Trier par',
        'sort.label': 'Trier par',
        'sort.alpha': 'Ordre alphabétique',
        'sort.date': 'Date d\'ajout',
        'sort.dateAdded': 'Date d\'ajout',
        'sort.last_opened': 'Dernière ouverture',
        'sort.lastOpened': 'Dernière ouverture',
        'view.grid': 'Grille',
        'view.list': 'Liste',
        'action.selectAll': 'Tout sélectionner',
        'grid.columns': 'Colonnes',
        "settings.save.button": "Sauvegarder les clés",
        "settings.save.saving": "Sauvegarde...",
        "settings.save.success": "Clés API sauvegardées avec succès !",
        "settings.save.error": "Erreur lors de la sauvegarde.",
        "settings.api.perplexity.default": "Perplexity AI (Par défaut)",
        "settings.api.perplexity.summaries": "Perplexity - Résumés",
        "settings.api.perplexity.exercises": "Perplexity - Exercices",
        "settings.api.gemini.vincent": "Google Gemini (Vincent Pena)",
        "settings.api.gemini.summaries": "Google Gemini - Résumés",
        "settings.api.gemini.exercises": "Google Gemini - Exercices",
        "settings.api.integrations": "Intégrations",
        "settings.api.calendar": "Autorisation Google Calendar",
        // Generation Menu
        "gen.menu.button": "Génération",
        "gen.menu.title": "Générer du contenu",
        "gen.flashcards.title": "Flashcards",
        "gen.flashcards.desc": "Cartes mémoire pour la mémorisation espacée.",
        "gen.quiz.title": "QCM Intelligent",
        "gen.quiz.desc": "Questions à choix multiples pour tester vos connaissances.",
        "gen.plan.title": "Plan de Révision",
        "gen.plan.desc": "Planning hebdomadaire généré par IA.",
        "gen.viewAll": "Voir tous mes exercices",
        "gen.empty": "Aucun excercice généré",
        "gen.start": "Utilisez le bouton Génération pour commencer.",
        "gen.list.cards": "cartes",
        "gen.list.questions": "Questions",
        "gen.list.mastery": "Maîtrise",
        "gen.action.start": "Commencer",
        "gen.action.quiz": "Passer le Quiz",
        "gen.delete.confirm": "Voulez-vous vraiment supprimer cet exercice ?",
        "gen.delete.error": "Erreur lors de la suppression",
        "common.open": "Ouvrir",
        "common.in": "dans",
        "changelog.v051.title": "Mobilité & Stabilité 📱⚡",
        "changelog.v051.mobile": "Optimisation Mobile : Refonte de la vue cours pour smartphone avec des cartes plus compactes et un en-tête intelligent.",
        "changelog.v051.folders": "Navigation Fluide : Les dossiers sont désormais ouverts par défaut pour un accès direct à vos cours.",
        "changelog.v051.office": "Lecteur Office Hybride : Passage au lecteur Google Docs pour une ouverture fiable des PPT et Excel.",
        "changelog.v051.api": "Intercepteur API : Détection automatique des sessions expirées et reconnexion intelligente.",
        "changelog.v051.deps": "Dépendances : Réparation des erreurs de compilation liées aux modules Word et HEIC.",
        "changelog.v051.prisma": "Synchro Prisma : Mise à jour du moteur de base de données pour une cohérence parfaite des types serveur.",
        "changelog.v050.title": "Stabilité & Intelligence 🧠",
        "changelog.v050.api_keys": "Persistance Clés API : Correction d'un bug critique où les clés disparaissaient.",
        "changelog.v050.logout": "Déconnexion Propre : Le bouton 'Déconnexion' nettoie maintenant correctement la session.",
        "changelog.v050.ai_reliability": "Fiabilité IA : Correction des erreurs 404/500 et meilleure gestion des quotas Gemini.",
        "changelog.v050.polish": "Polissage Localisation : Traductions françaises corrigées et thème 'Minecraft' partout.",
        "changelog.v041.title": "Hub de Ressources 📂",
        "changelog.v041.viewer": "Visionneuse Multi-Format : Support natif des PDF, documents Office (Word, Excel, PowerPoint) et images directement dans l'app.",
        "changelog.v041.metadata": "Métadonnées : Cartes de ressources plus claires affichant format, date et nom complet.",
        "changelog.v041.delete_fix": "Suppression Sécurisée : Correction des erreurs 'Fichier non trouvé' et ajout de feedback visuel.",
        "changelog.v041.doc_type": "Détection Doc : Détection robuste du type de fichier assurant l'ouverture dans la bonne visionneuse.",
        "changelog.v040.title": "Refonte Synchro Cloud 🔄",
        "changelog.v040.infra": "Infrastructure Sync : Backend de synchronisation entièrement refait pour corriger l'authentification.",
        "changelog.v040.upload": "Upload Fichiers : Résolution des erreurs 404 (Nginx).",
        "changelog.v040.schema": "Schéma Base de Données : Correction génération UUID pour dossiers et cours.",
        "changelog.v040.speed": "Vitesse Sync : Intervalle réduit de 30s à 3s pour des mises à jour quasi-instantanées.",
        "changelog.v040.cleanup": "Nettoyage Intelligent : Suppression auto des vieux enregistrements (>7 jours).",
        "changelog.v040.tombstone": "Optimisation Tombstone : Synchro des suppressions sur 24h seulement.",
        "changelog.v040.nginx": "Config Nginx : Correction du routage API (/api/, /auth/, /sync).",
        "changelog.v030.title": "Focus & Localisation 🌍",
        "changelog.v030.focus": "Mode Focus : Résumés en plein écran sans distraction.",
        "changelog.v030.multilang": "Multi-Langue : Disponible en Anglais, Français et... Minecraft ?",
        "changelog.v030.ai2": "Résumés IA 2.0 : Utilise Gemini pour des résumés plus pertinents.",
        "changelog.v030.export": "Export Amélioré : Téléchargement en PDF et Word (.docx).",
        "changelog.v020.title": "Export PDF & Recherche",
        "changelog.v020.pdf": "Export PDF : Génération de PDF professionnels pour vos résumés.",
        "changelog.v020.command": "Centre de Commande : `Cmd+K` pour tout rechercher instantanément.",
        "changelog.v020.analytics": "Analytics : Timeline d'activité.",
        "changelog.v020.large_files": "Optimisation gros fichiers.",
        "changelog.v015.title": "Structure & Organisation",
        "changelog.v015.recursive": "Dossiers Récursifs : Arborescence infinie.",
        "changelog.v015.favorites": "Favoris Rapides : Épinglez vos cours importants.",
        "changelog.v015.dnd": "Drag & Drop : Réorganisation intuitive.",
        "changelog.v010.title": "Genèse",
        "changelog.v010.engine": "Moteur d'Apprentissage : Cours, Notes, Exercices.",
        "changelog.v010.graph": "Graphe de Connaissances : Visualisation interactive.",
        "changelog.current": "ACTUEL"
    },
    mc: {
        "app.title": "EduCraft",
        "nav.myCourses": "My Worlds",
        "nav.noCourses": "No worlds generated yet.",
        "nav.newCourse": "New World",
        "nav.settings": "Server Props",
        "nav.selectProfile": "Choose a character first!",
        "dashboard.stats.courses": "Worlds",
        "dashboard.stats.exercises": "Quests",
        "dashboard.stats.notes": "Books",
        "dashboard.recent": "Recent Worlds",
        "dashboard.inprogress": "Raiding",
        "dashboard.activity": "Server Logs",
        "dashboard.empty.courses": "No worlds yet.",
        "dashboard.empty.activity": "No logs.",
        "changelog.title": "Patch Notes",
        "changelog.view": "Read Patch Notes",
        "changelog.desc": "Check the server version history.",
        "course.create.title": "Generate New World",
        "course.create.name": "World Name",
        "course.create.desc": "Seed Info / Biome Data",
        "course.create.color": "Dye Color",
        "course.create.cancel": "Respawn",
        "course.create.submit": "Craft World",
        "course.create.loading": "Generating chunks...",
        "course.delete.confirm": "Are you sure you want to drop this item into lava? All data will be lost.",
        "item.delete.confirm": "Throw this item into cactus?",
        "course.notFound": "Chunks not loaded...",
        "course.addContent": "Craft Item",
        "course.tabs.all": "Inventory",
        "course.tabs.exercises": "Quests",
        "course.tabs.notes": "Books",
        "course.tabs.resources": "Loot",
        "course.empty": "Inventory empty.",
        "course.search": "Locate item...",
        "item.create.title": "Crafting Table",
        "item.create.type.note": "Book & Quill",
        "item.create.type.exercise": "Quest",
        "item.create.type.resource": "Map",
        "item.form.title": "Item Name",
        "item.form.title.placeholder.note": "e.g. Book of Spells",
        "item.form.title.placeholder.exercise": "e.g. Ender Dragon Raid",
        "item.form.title.placeholder.resource": "e.g. Biome Map",
        "item.form.content": "Pages / Data",
        "item.form.status": "Quest State",
        "item.form.difficulty": "Mob Level",
        "item.form.desc": "Lore",
        "item.form.file": "Schematic",
        "item.form.file.placeholder": "Drop item stack here",
        "item.form.file.supports": "Supports Maps, Paintings",
        "item.form.submit.note": "Sign Book",
        "item.form.submit.exercise": "Start Quest",
        "item.form.submit.resource": "Store in Chest",
        "status.todo": "Spawned",
        "status.in-progress": "Raiding",
        "status.completed": "Defeated",
        "diff.easy": "Peaceful",
        "diff.medium": "Normal",
        "diff.hard": "Hardcore",
        "theme.toggle": "Toggle Day/Night",
        "lang.toggle": "Language",
        "welcome.title": "Reviewing Server",
        "welcome.subtitle": "Select a world to teleport to.",
        "welcome.card.title": "Spawn Point",
        "welcome.card.desc": "Generate a new world in the sidebar.",
        "profiles.manager.title": "World Ops",
        "profiles.dropdown.select": "Select Entity",
        "profiles.dropdown.switch": "Switch Dimension",
        "profiles.dropdown.add": "Spawn Guest",
        "profiles.dropdown.manage": "Server Settings",
        "profiles.dropdown.logout": "Quit Game (Close)",
        "drop.title": "Drop stack to upload",
        "folder.new": "New Biome",
        "folder.create.sub": "New Chunk",
        "folder.create.prompt": "Name this region:",
        "folder.delete.confirm": "Destroy this biome? Mobs will migrate to neighbor.",
        "settings.title": "World Options",
        "action.delete": "Destroy Block",
        "action.cancel": "Sneak",
        // Search
        "search.placeholder": "Locate intentory items...",
        "search.noResults": "No entities found for",
        "search.type": "Use /locate...",
        "search.searching": "Chunk loading...",
        "search.results": "entities",
        "search.nav": "fly",
        "search.select": "interact",
        // Summary
        "summary.title": "Enchantment Table Options",
        "summary.compression": "Simplification Level",
        "summary.format": "Scroll Format",
        "summary.preserveHeadings": "Keep Runes",
        "summary.detectKeywords": "Detect Spells (Formulas)",
        "summary.desc.20": "Level 1. Basic runes only.",
        "summary.desc.40": "Level 30. Balanced enchant.",
        "summary.desc.50": "God Roll. Max info.",
        "summary.generate": "Enchant Item",
        "summary.generated": "Enchanted Scroll",
        "summary.copy": "Copy to Chat",
        "summary.regenerate": "Re-roll Enchant",
        "summary.configure": "Anvil",
        "summary.view": "Read Scroll",
        "summary.hide": "Close Scroll",
        "summary.trigger": "Enchant",
        "summary.stats.words": "Runes",
        "summary.stats.ratio": "Power",
        "summary.stats.time": "Ticks",
        "summary.error.noContent": "The scroll is blank! No readable runes found. (PDFs not supported)",
        "summary.fmt.bullets": "List",
        "summary.fmt.paragraph": "Book",
        "summary.fmt.outline": "Map",
        "summary.fmt.timeline": "History",
        "summary.provider": "Enchantment Source",
        "summary.error.ai": "The scroll failed to enchant! Check your Redstone.",
        // Common / Folder
        "common.folder": "Biome",
        "common.noDesc": "No Lore",
        "folder.empty": "Void biome.",
        // New Additions
        "focus.enter": "Focus Beacon",
        "focus.exit": "Leave Beacon Range",
        "focus.enter.tooltip": "Activate Focus Beacon",
        "focus.exit.tooltip": "Deactivate Beacon (Esc)",
        "summary.generating": "Scribing enchantment in progress...",
        "summary.error.display": "The scroll is cursed/unreadable.",
        "file.unknownSize": "Unknown weight",
        "file.attached": "Attached Loot",
        "file.download": "Pick Block",
        "course.return": "Teleport to World",
        "export.defaultTitle": "Enchanted_Scroll",
        "export.generatedOn": "Crafted on:",
        "export.contentComplex": "NBT Data",
        // Settings Page
        "settings.page.title": "Server Properties",
        "settings.page.subtitle": "Configure game rules and world settings.",
        "settings.tabs.api": "Command Blocks & API",
        "settings.tabs.appearance": "Resource Packs",
        "settings.tabs.shortcuts": "Keybinds",
        "settings.api.title": "Redstone Circuits",
        "settings.api.desc": "Link your command blocks to external servers.",
        "settings.appearance.title": "Resource Packs",
        "settings.appearance.desc": "Change textures and shaders.",
        "settings.shortcuts.title": "Keybinds",
        "settings.shortcuts.desc": "Customize controls.",
        "settings.shortcuts.global": "Movement & Admin",
        "settings.shortcuts.flashcards": "Combat",
        "settings.theme.light": "Overworld (Day)",
        "settings.theme.dark": "The End (Night)",
        "settings.theme.system": "Redstone Lamp",
        "settings.save.button": "Save to Chunk",
        "settings.save.saving": "Saving Level...",
        "settings.save.success": "Level.dat saved!",
        "settings.save.error": "Corrupted Chunk!",
        "settings.api.perplexity.default": "Default Server",
        "settings.api.perplexity.summaries": "Librarian Trade",
        "settings.api.perplexity.exercises": "Combat Training",
        "settings.api.gemini.vincent": "Vincent's Server",
        "settings.api.gemini.summaries": "Gemini Trade",
        "settings.api.gemini.exercises": "Gemini Quest",
        "settings.api.integrations": "Mod Integrations",
        "settings.api.calendar": "Daylight Cycle",
        // Generation Menu
        "gen.menu.button": "Spawn Logic",
        "gen.menu.title": "Spawn Mobs/Items",
        "gen.flashcards.title": "Mob Spawner",
        "gen.flashcards.desc": "Spawn entities for XP farming.",
        "gen.quiz.title": "Dungeon Trial",
        "gen.quiz.desc": "Test your survival skills.",
        "gen.plan.title": "Adventure Map",
        "gen.plan.desc": "Generate a quest path.",
        "gen.viewAll": "Open Quest Log",
        "gen.empty": "Mob cap reached (Empty)",
        "gen.start": "Use Spawner Egg",
        "gen.list.cards": "mobs",
        "gen.list.questions": "challenges",
        "gen.list.mastery": "XP Level",
        "gen.action.start": "Enter Dungeon",
        "gen.action.quiz": "Accept Challenge",
        "gen.delete.confirm": "Despawn this entity?",
        "gen.delete.error": "Chunk error!",
        "common.open": "Teleport",
        "common.in": "in",
        "sort.label": "Order:",
        "sort.dateAdded": "Spawn Time",
        "sort.alphabetical": "A-Z Scrolls",
        "sort.lastOpened": "Last Traveled",
        "grid.columns": "Chunks",
        "bulk.selected_singular": "Entity selected",
        "bulk.selected_plural": "Entities selected",
        "action.selectAll": "Select All Chunks",
        "changelog.v051.title": "Mobility & Stability 📱⚡",
        "changelog.v051.mobile": "Pocket UI: Reworked the world view for small maps with compact item stacks.",
        "changelog.v051.folders": "Open Portals: Biomes are now open by default for faster travel.",
        "changelog.v051.office": "Hybrid Scroll Viewer: Use Google Scrolls to read PPT/Excel loot.",
        "changelog.v051.api": "Server Interceptor: Auto-reconect when connection to the realm is lost.",
        "changelog.v051.deps": "Modpacks: Fixed conflict between Word and HEIC mod files.",
        "changelog.v051.prisma": "Core Update: Optimized the NBT data engine for server stability.",
        "changelog.v050.title": "Stability & Intelligence 🧠",
        "changelog.v050.api_keys": "Saving Level.dat: Fixed a bug where world keys were lost.",
        "changelog.v050.logout": "Safe Quit: The 'Quit' button now properly saves your player state.",
        "changelog.v050.ai_reliability": "Reliable NPCs: Fixed Villager trade errors and Gemini quota management.",
        "changelog.v050.polish": "Texture Pack: Polished English labels and Minecraft mode everywhere.",
        "changelog.v041.title": "Loot Hub 📂",
        "changelog.v041.viewer": "Omni-Lens: Native support for PDF scrolls, Books and Maps.",
        "changelog.v041.metadata": "NBT Tags: Clearer loot cards showing durability and enchants.",
        "changelog.v041.delete_fix": "TNT Deletion: Fixed 'Block not found' errors.",
        "changelog.v041.doc_type": "Item Sorting: Enhanced item detection system.",
        "changelog.v040.title": "Realm Sync 🔄",
        "changelog.v040.infra": "Multiplayer Backend: Reworked the synchronization core.",
        "changelog.v040.upload": "Item Drop: Fixed item pickup failures.",
        "changelog.v040.schema": "World Gen: Fixed UUID generation for chunks and biomes.",
        "changelog.v040.speed": "Tick Rate: Reduced sync delay for instant interaction.",
        "changelog.v030.title": "Beacon & Shaders 🌍",
        "changelog.v030.focus": "Beacon Mode: Scribe summaries without distraction from Creepers.",
        "changelog.v030.multilang": "Villager Trades: Multi-language support added (including Minecraftian!).",
        "changelog.v030.ai2": "Redstone Logic 2.0: Improved AI scrolls for better loot data.",
        "changelog.v030.export": "Scroll Export: Download your books as .pdf and .docx loot.",
        "changelog.v020.title": "Scroll Export & Locate",
        "changelog.v020.pdf": "Professional Scrolls: Enchanted PDF generation.",
        "changelog.v020.command": "Cheat Code: `Cmd+K` to locate any block instantly.",
        "changelog.v020.analytics": "Server Stats: See your activity timeline.",
        "changelog.v020.large_files": "Bedrock Optimization: Smooth handling of massive schematics.",
        "changelog.v015.title": "Chunks & Organisation",
        "changelog.v015.recursive": "Infinite Biomes: Recursive folder structure.",
        "changelog.v015.favorites": "Hotbar: Pin your most expensive loot for quick access.",
        "changelog.v015.dnd": "Inventory Sort: Drag & drop items to reorder chunks.",
        "changelog.v010.title": "The Big Bang",
        "changelog.v010.engine": "Game Engine: Worlds, Books, Quests.",
        "changelog.v010.graph": "Map Room: Visualized knowledge graph.",
        "changelog.current": "LIVE"
    }
}

type LanguageProviderProps = {
    children: React.ReactNode
    defaultLanguage?: Language
    storageKey?: string
}

type LanguageProviderState = {
    language: Language
    setLanguage: (language: Language) => void
    t: (key: string) => string
}

const initialState: LanguageProviderState = {
    language: "en",
    setLanguage: () => null,
    t: (key) => key,
}

const LanguageProviderContext = createContext<LanguageProviderState>(initialState)

export function LanguageProvider({
    children,
    defaultLanguage = "en",
    storageKey = "vite-ui-language",
    ...props
}: LanguageProviderProps) {
    const [language, setLanguage] = useState<Language>(
        () => (localStorage.getItem(storageKey) as Language) || defaultLanguage
    )

    useEffect(() => {
        localStorage.setItem(storageKey, language)

        // Global Theme Injection for Minecraft Mode
        if (language === 'mc') {
            document.body.classList.add('minecraft-theme')
        } else {
            document.body.classList.remove('minecraft-theme')
        }
    }, [language, storageKey])

    const t = (key: string) => {
        return translations[language][key] || key
    }

    const value = {
        language,
        setLanguage,
        t
    }

    return (
        <LanguageProviderContext.Provider value={value} {...props}>
            {children}
        </LanguageProviderContext.Provider>
    )
}

export const useLanguage = () => {
    const context = useContext(LanguageProviderContext)

    if (context === undefined)
        throw new Error("useLanguage must be used within a LanguageProvider")

    return context
}
