import { createContext, useContext, useEffect, useState } from "react"

export type Language = "en" | "fr" | "mc"

type Translations = {
    [key in Language]: {
        [key: string]: string
    }
}

const translations: Translations = {
    en: {
        "app.title": "EduTrack",
        "nav.myCourses": "My Courses",
        "nav.noCourses": "No courses yet.",
        "nav.newCourse": "New Course",
        "nav.board": "Investigation Board",
        "nav.library": "Library",
        "nav.explore": "Explore",
        "nav.settings": "Settings",
        "nav.selectProfile": "Select a profile first",
        "board.subtitle": "Explore your knowledge base",
        "board.mode": "Detective Board",
        "course.create.title": "Create New Course",
        "course.create.name": "Course Title",
        "course.create.desc": "Description (Optional)",
        "course.create.color": "Color Tag",
        "course.create.cancel": "Cancel",
        "course.create.submit": "Create Course",
        "course.create.loading": "Creating...",
        "course.move.success": "Course moved successfully",
        "course.delete.confirm": "Are you sure you want to delete this course? All items will be lost.",
        "item.delete.confirm": "Are you sure you want to delete this item?",
        "course.notFound": "Course not found or loading...",
        "course.addContent": "Add Content",
        "course.tabs.all": "All Content",
        "course.tabs.exercises": "Exercises",
        "course.tabs.notes": "Notes",
        "course.tabs.resources": "Resources",
        "course.empty": "No items found in this section.",
        "course.search": "Search items...",
        "item.create.title": "Add Content",
        "item.create.type.note": "Note",
        "item.create.type.exercise": "Exercise",
        "item.create.type.resource": "Resource",
        "item.form.title": "Title",
        "item.form.title.placeholder.note": "e.g. Lecture Summary",
        "item.form.title.placeholder.exercise": "e.g. Calculus Drill 1",
        "item.form.title.placeholder.resource": "e.g. Textbook PDF",
        "item.form.content": "Content",
        "item.form.status": "Status",
        "item.form.difficulty": "Difficulty",
        "item.edit.error": "Failed to update item",
        "item.edit.save": "Save Changes",
        "item.edit.save_loading": "Updating...",
        "item.edit.drop_file": "Drop file to attach",
        "common.optional": "Optional",
        "item.form.desc": "Description",
        "item.form.file": "File",
        "item.form.file.placeholder": "Click or drag file here",
        "item.form.file.supports": "Supports PDF, Images, ZIP",
        "item.form.submit.note": "Create Note",
        "item.form.submit.exercise": "Create Exercise",
        "item.form.submit.resource": "Create Resource",
        "item.noContent": "No content to display.",
        "item.startWriting": "Start writing",
        "status.todo": "To Do",
        "status.in-progress": "In Progress",
        "status.completed": "Completed",
        "diff.easy": "Easy",
        "diff.medium": "Medium",
        "diff.hard": "Hard",
        "lang.toggle": "Language", // Generic label for dropdown
        "welcome.empty.title": "Start your Learning Journey",
        "welcome.empty.desc": "Create your first course to begin tracking your progress.",
        "welcome.create.button": "Create First Course",
        "welcome.title": "Welcome back!",
        "welcome.subtitle": "Select a course to start learning or manage your content.",
        "welcome.card.title": "Getting Started",
        "welcome.card.desc": "Create your first course using the sidebar.",
        "profiles.manager.title": "Manage Profiles",
        "profiles.dropdown.select": "Select Profile",
        "profiles.dropdown.switch": "Switch Profile",
        "profiles.dropdown.add": "Add Profile",
        "profiles.dropdown.manage": "Manage Profiles",
        "profiles.dropdown.logout": "Logout (Close Profile)",
        "dashboard.stats.courses": "Courses",
        "dashboard.stats.exercises": "Exercises",
        "dashboard.stats.notes": "Notes",
        "dashboard.stats.aiGeneration": "AI Generation",
        "dashboard.recent": "Recent Courses",
        "dashboard.inprogress": "In Progress",
        "dashboard.activity": "Activity Log",
        "dashboard.empty.courses": "No courses yet.",
        "dashboard.empty.activity": "No recent activity.",
        "changelog.title": "What's New",
        "changelog.view": "View Changelog",
        "changelog.desc": "View the update history.",
        "drop.title": "Drop file to upload",
        "folder.new": "New Subject",
        "folder.create.sub": "New Sub-Folder",
        "folder.create.prompt": "Enter folder name:",
        "folder.delete.confirm": "Delete this folder? Content will move to parent.",
        "settings.title": "Course Settings",
        "action.delete": "Delete",
        "action.cancel": "Cancel",
        "action.close": "Close",
        "action.openNewTab": "Open in new tab",
        "action.fullscreen": "Fullscreen (Local)",
        "action.zoomOut": "Zoom out",
        "action.zoomIn": "Zoom in",
        "action.rotate": "Rotate",
        "action.expand": "Expand",
        "action.download": "Download",
        "action.copy": "Copy to clipboard",
        "action.summarize": "Summarize",
        "action.preview": "Preview",
        "action.refresh": "Refresh",
        "export.pdf": "Export PDF",
        "export.word": "Export Word",
        "export.anki": "Export Anki",
        "document.fullscreen": "Document Fullscreen",
        "document.pdf": "PDF Document",
        "document.viewer": "Document Viewer",
        "office.switchViewer": "Switch viewer if display bugs",
        "profile.delete.tooltip": "Delete Profile",
        "sidebar.expandTimer": "Expand to see Timer",
        "timer.reset": "Reset Timer",
        "theme.toggle": "Toggle theme",
        "calendar.autoDetect": "Auto-detect from Google Calendar",
        "file.thumbnail": "File Thumbnail",
        "icon.none": "No Icon",
        // Search
        "search.placeholder": "Search courses, notes, exercises...",
        "search.noResults": "No results found for",
        "search.type": "Type to search...",
        "search.searching": "Searching...",
        "search.results": "results",
        "search.nav": "to navigate",
        "search.select": "to select",
        // Summary
        "summary.title": "Summarization Options",
        "summary.compression": "Compression",
        "summary.format": "Format",
        "summary.preserveHeadings": "Preserve Headings",
        "summary.detectKeywords": "Detect Keywords (Formulas, Dates)",
        "summary.useWebSearch": "Active Web Research (Perplexity)",
        "summary.desc.20": "Ultra-short. Definitions & key formulas only.",
        "summary.desc.40": "Balanced. Recommended for general study.",
        "summary.desc.50": "Detailed. Includes examples and context.",
        "summary.generate": "Generate Summary",
        "summary.generated": "Generated Summary",
        "summary.copy": "Copy to clipboard",
        "summary.regenerate": "Regenerate",
        "summary.configure": "Configure",
        "summary.view": "View Summary",
        "summary.hide": "Hide Summary",
        "summary.trigger": "Summarize",
        "summary.stats.words": "Words",
        "summary.stats.ratio": "Ratio",
        "summary.stats.time": "Time",
        "summary.error.noContent": "No text content found to summarize. PDF/Image content is not currently supported.",
        "summary.fmt.bullets": "Bullets",
        "summary.fmt.paragraph": "Paragraph",
        "summary.fmt.outline": "Outline",
        "summary.fmt.timeline": "Timeline",
        "summary.provider": "Generator Model",
        "summary.error.ai": "AI Generation Failed. Check if API keys are valid.",
        // Common / Folder
        "common.folder": "Folder",
        "common.save": "Save",
        "common.saving": "Saving...",
        "common.noDesc": "No description",
        "folder.empty": "This folder is empty.",
        // Board
        "board.mapTitle": "Investigation Board",
        "board.orphans": "Orphan Courses",
        "board.noOrphans": "No orphan courses found.",
        "board.caseFile": "Case File",
        "board.search.placeholder": "Search...",
        "board.type": "Type: ",
        "board.doubleClickOpen": "Double-click to open",
        "board.containsItems": "Contains {{count}} items",
        "board.document": "Document",
        "board.upload": "Upload",
        "board.assign": "Assign",
        "common.topics": "Topics",
        "common.courses": "Courses",
        "common.documents": "Documents",
        "action.filter": "Filters",
        "action.fitView": "Fit View",
        "action.resetLayout": "Reset Layout",
        "action.export": "Export",
        "action.assign": "Assign",
        "action.upload": "Upload",
        "action.enterZen": "Enter Zen Mode",
        "action.exitZen": "Exit Zen Mode",
        // Item Edit
        "item.edit": "Edit Item",
        "item.edit.title": "Edit Item",
        "item.edit.replaceFile": "Replace File",
        "item.edit.keepFile": "Keep Current File",
        "item.edit.success": "Item updated successfully",
        "profile.create.name.placeholder": "e.g. Jean Dupont",
        "profile.create.email.placeholder": "jean@example.com",
        "settings.api.placeholder.pplx": "pplx-...",
        "settings.api.placeholder.gemini": "AIza...",
        "settings.api.placeholder.bearer": "Bearer ...",
        "course.create.name.placeholder": "e.g. Advanced Calculus",
        "course.create.desc.placeholder": "Brief summary of the course...",
        "item.form.instructions.placeholder": "Instructions for the exercise...",
        "calendar.noEvents": "No events",
        "calendar.allDay": "All Day",
        "calendar.synced": "Synced",
        "calendar.connected": "Connected",
        "calendar.connect": "Connect Google Calendar",
        "calendar.connecting": "Connecting...",
        // New Additions
        "app.search": "Search...",
        "focus.enter": "Focus Mode",
        "focus.exit": "Exit Focus",
        "focus.enter.tooltip": "Enter Focus Mode",
        "focus.exit.tooltip": "Exit Focus Mode (Esc)",
        "focus.mode": "Focus Mode",
        "focus.work": "Focus",
        "focus.shortBreak": "Short Break",
        "focus.longBreak": "Long Break",
        "focus.current": "Current Focus",
        "focus.ready": "Ready",
        "focus.active": "In Progress",
        "action.pause": "Pause",
        "action.start": "Start",
        "summary.generating": "Drafting academic summary...",
        "summary.error.display": "Error displaying summary.",
        "file.unknownSize": "Unknown size",
        "file.attached": "Attached File",
        "file.download": "Download",
        "course.return": "Back to Course",
        "export.defaultTitle": "Summary",
        "export.generatedOn": "Generated on:",
        "export.contentComplex": "Complex content",
        "bulk.selected_singular": "Item selected",
        "bulk.selected_plural": "Items selected",
        "bulk.generate": "Generate",
        "bulk.generate.flashcards": "Flashcards",
        "bulk.generate.quiz": "Quiz",
        "bulk.generate.summary": "Summary",
        "common.delete": "Delete",
        "common.cancel": "Cancel",
        "common.back": "Back",
        // Settings Page
        "settings.page.title": "Settings",
        "settings.page.subtitle": "Manage your global preferences and configurations.",
        "settings.tabs.api": "API Keys & Services",
        "settings.tabs.appearance": "Appearance",
        "settings.tabs.shortcuts": "Keyboard Shortcuts",
        "settings.api.title": "Service Configuration",
        "settings.api.desc": "Configure API keys for AI services and integrations.",
        "settings.appearance.title": "Appearance",
        "settings.appearance.desc": "Customize the application look and feel.",
        "settings.shortcuts.title": "Keyboard Shortcuts",
        "settings.shortcuts.desc": "Master the app with quick commands.",
        "settings.shortcuts.global": "Global Navigation",
        "settings.shortcuts.flashcards": "Flashcards",
        "settings.theme.light": "Light",
        "settings.theme.dark": "Dark",
        "settings.theme.system": "System",

        'sort.by': 'Sort by',
        'sort.label': 'Sort by',
        'sort.alpha': 'Alphabetical',
        'sort.alphabetical': 'Alphabetical',
        'sort.date': 'Date added',
        'sort.dateAdded': 'Date added',
        'sort.last_opened': 'Last opened',
        'sort.lastOpened': 'Last opened',
        'view.grid': 'Grid',
        'view.list': 'List',
        'action.selectAll': 'Select All',
        'grid.columns': 'Columns',
        "settings.save.button": "Save Keys",
        "settings.save.saving": "Saving...",
        "settings.save.success": "API Keys saved successfully!",
        "settings.save.error": "Error saving keys.",
        "settings.api.perplexity.default": "Perplexity AI (Default)",
        "settings.api.perplexity.summaries": "Perplexity - Summaries",
        "settings.api.perplexity.exercises": "Perplexity - Exercises",
        "settings.api.gemini.vincent": "Google Gemini (Vincent Pena)",
        "settings.api.gemini.summaries": "Google Gemini - Summaries",
        "settings.api.gemini.exercises": "Google Gemini - Exercises",
        "settings.api.integrations": "Integrations",
        "settings.api.calendar": "Google Calendar Authorization",
        // Generation Menu
        "gen.menu.button": "AI Generation",
        "gen.menu.title": "Generate Content",
        "gen.flashcards.title": "Flashcards",
        "gen.flashcards.desc": "Memory cards for spaced repetition.",
        "gen.quiz.title": "Smart Quiz",
        "gen.quiz.desc": "Multiple choice questions to test knowledge.",
        "gen.plan.title": "Study Plan",
        "gen.plan.desc": "AI-powered weekly schedule.",
        "gen.viewAll": "View all exercises",
        "gen.empty": "No generated content",
        "gen.start": "Start items",
        "gen.list.cards": "cards",
        "gen.list.questions": "Qs",
        "gen.list.mastery": "Mastery",
        "gen.action.start": "Start",
        "gen.action.quiz": "Take Quiz",
        "gen.delete.confirm": "Do you really want to delete this exercise?",
        "gen.delete.error": "Error during deletion",
        "common.open": "Open",
        "common.in": "in",

        // TTS
        "tts.play": "Read Aloud",
        "tts.pause": "Pause",
        "tts.resume": "Resume",
        "tts.stop": "Stop",
        "tts.speed": "Speed",
        "tts.unsupported": "Text-to-Speech is not supported in your browser",
        "tts.error": "Failed to read text",
        "tts.reading": "Reading...",

        // STT
        "stt.start": "Start Dictation",
        "stt.stop": "Stop Dictation",
        "stt.listening": "Listening...",
        "stt.unsupported": "Speech-to-Text not supported",
        "stt.error.permission": "Microphone Access Denied",
        "stt.error.https": "Speech recognition requires a secure HTTPS connection (or localhost).",
        "stt.error.blocked": "Please allow microphone access in your browser settings.",
        "stt.error.generic": "Speech recognition failed.",

        "changelog.v051.title": "Mobility & Stability 📱⚡",
        "changelog.v051.mobile": "Mobile Optimization: Reworked Course View for smartphones with compact cards, an intelligent header, and optimized file previews.",
        "changelog.v051.folders": "Fluid Navigation: Folders are now open by default and breadcrumbs are improved for better hierarchy awareness.",
        "changelog.v051.office": "Hybrid Office Viewer: Integrated Google Docs Viewer for reliable previewing of PowerPoint and Excel files.",
        "changelog.v051.api": "Core Stability: Fixed API session persistence, 401 interceptors, and critical dependency errors.",
        "changelog.v051.polish": "UI & Localization: 100% translation coverage (EN/FR/Minecraft), fixed modal backgrounds, and optimized list view displays.",
        "changelog.v052.title": "Productivity & Revisions 🚀",
        "changelog.v052.revision": "AI Revision Plan: Generate your personalized study schedule in one click.",
        "changelog.v052.edit": "Quick Edit: Modify items and replace files without recreating everything.",
        "changelog.v052.vscode": "VS Code Sync: Open your code projects directly in VS Code from the app.",
        "changelog.v052.pptx": "Office Web Support: Preview PPTX/DOCX now compatible via Google/Microsoft Viewers.",
        "changelog.v052.ui": "UI Fixes: Visual improvements (menu centering, borders).",
        "changelog.v053.title": "Performance & Speed ⚡",
        "changelog.v053.perf": "PageSpeed: Score boosted from 53 to 90+.",
        "changelog.v053.cache": "Smart Caching: Assets are now cached for instant revisits.",
        "changelog.v053.lazy": "Lazy Loading: Initial load is faster thanks to code splitting.",
        "changelog.v053.images": "Optimized Assets: Images are compressed and decoded asynchronously.",

        // v0.5.8
        "changelog.v058.title": "Voice & Accessibility 🗣️",
        "changelog.v058.tts": "Text-to-Speech: Listen to your notes with multilang support and speed control.",
        "changelog.v058.stt": "Speech-to-Text: Dictate your content directly into the editor.",
        "changelog.v058.library": "Library Page: A dedicated space to browse and filter all your courses.",
        "changelog.v058.dashboard": "Dashboard Refinements: Improved layout and added a compact focus timer to the header.",

        // v0.5.9
        "changelog.v059.title": "Focus & Aesthetics 🎨",
        "changelog.v059.analytics": "Focus Analytics: Detailed session tracking and weekly productivity charts.",
        "changelog.v059.themes": "Custom Themes: Personalize your experience with new 'Nature' and 'Sunset' color palettes.",
        "changelog.v059.dashboard": "Dashboard Light Mode: Hero section now supports a clean light theme for better visibility.",
        "changelog.v059.notes": "Note Standardization: Improved note layout to match the editor's visual structure.",

        // v1.3.0
        "changelog.v130.title": "Performance & Mobile 🚀",
        "changelog.v130.mobile": "Mobile Experience: Redesigned resource viewer with full-screen support and optimized buttons.",
        "changelog.v130.performance": "Lightning Fast: Improved load times by 40% with smart code-splitting and optimized assets.",
        "changelog.v130.documents": "Document Import Fix: You can now attach files to exercises without errors.",
        "changelog.v130.ai": "AI Updates: Latest Gemini 2.5 models with improved reliability.",

        // v0.5.4
        "changelog.v054.title": "Power User Update",
        "changelog.v054.board": "Added Investigation Board view for visual knowledge mapping.",
        "changelog.v054.command": "Introduced Global Command Center (Ctrl+K) for instant navigation.",
        "changelog.v054.focus": "Added Focus Mode with integrated Pomodoro Timer.",
        "changelog.v054.sidebar": "Collapsible Sidebar for maximized workspace.",
        "changelog.v050.title": "Stability & Intelligence 🧠",
        "changelog.v050.api_keys": "API Key Persistence: Critical fix for disappearing keys. They are now stored securely.",
        "changelog.v050.logout": "Clean Logout: The 'Logout' button now correctly cleans up the session and token.",
        "changelog.v050.ai_reliability": "AI Reliability: Fixed 404/500 errors during flashcard generation and better Gemini quota management.",
        "changelog.v050.polish": "Localization Polish: Fixed French translations and ensured the 'Minecraft' theme applies everywhere.",
        "changelog.v041.title": "Resource Hub 📂",
        "changelog.v041.viewer": "Multi-Format Viewer: Native support for PDF, Office docs (Word, Excel, PowerPoint) and images directly in the app.",
        "changelog.v041.metadata": "Metadata: Clearer resource cards showing format, date and full name.",
        "changelog.v041.delete_fix": "Secure Deletion: Fixed 'File not found' errors and added visual feedback.",
        "changelog.v041.doc_type": "Doc Detection: Robust file type detection ensuring opening in the correct viewer.",
        "changelog.v040.title": "Cloud Sync Overhaul 🔄",
        "changelog.v040.infra": "Sync Infrastructure: Backend synchronization entirely rebuilt to fix authentication and routing.",
        "changelog.v040.upload": "File Upload: Resolved 404 errors (Nginx).",
        "changelog.v040.schema": "Database Schema: Fixed UUID generation for folders and courses.",
        "changelog.v040.speed": "Sync Speed: Interval reduced from 30s to 3s for near-instant updates.",
        "changelog.v040.cleanup": "Smart Cleanup: Auto-deletion of old records (>7 days).",
        "changelog.v040.tombstone": "Tombstone Optimization: Deletion sync over 24h only.",
        "changelog.v040.nginx": "Nginx Config: Fixed API routing (/api/, /auth/, /sync).",
        "changelog.v030.title": "Focus & Localization 🌍",
        "changelog.v030.focus": "Focus Mode: Fullscreen summaries without distraction.",
        "changelog.v030.multilang": "Multi-Language: Available in English, French and... Minecraft?",
        "changelog.v030.ai2": "AI Summaries 2.0: Uses Gemini for more relevant summaries.",
        "changelog.v030.export": "Improved Export: Download in PDF and Word (.docx).",
        "changelog.v020.title": "PDF Export & Search",
        "changelog.v020.pdf": "PDF Export: Professional PDF generation for your summaries.",
        "changelog.v020.command": "Command Center: `Cmd+K` to search everything instantly.",
        "changelog.v020.analytics": "Analytics: Activity timeline.",
        "changelog.v020.large_files": "Optimization for large files.",
        "changelog.v015.title": "Structure & Organization",
        "changelog.v015.recursive": "Recursive Folders: Infinite tree structure.",
        "changelog.v015.favorites": "Quick Favorites: Pin your important courses.",
        "changelog.v015.dnd": "Drag & Drop: Intuitive reorganization.",
        "changelog.v010.title": "Genesis",
        "changelog.v010.engine": "Learning Engine: Courses, Notes, Exercises.",
        "changelog.v010.graph": "Knowledge Graph: Interactive visualization.",
        "changelog.current": "CURRENT",
        // Revision Program
        "revision.program": "Study Program",
        "revision.generate": "Generate Program",
        "revision.selectTarget": "Select Course or Folder",
        "revision.examDate": "Exam Date",
        "revision.noCalendar": "No calendar linked",
        "revision.linkCalendar": "Link a Calendar",
        "revision.availableTime": "Available Study Time",
        "revision.hours": "Hours",
        "revision.days": "Days",
        "revision.generating": "Generating your personalized study plan...",
        "plan.calendar.notConnected": "Please connect your Google Calendar first.",
        "plan.calendar.found": "Found exam: {event} on {date}",
        "plan.calendar.notFound": "No event found for '{course}'",
        "plan.calendar.error": "Calendar sync failed.",
        "plan.error.noDeadline": "Please select a deadline.",
        "plan.success": "Study Plan Generated Successfully!",
        "plan.error.failed": "Failed to generate plan.",
        // Auth
        "auth.welcome.back": "Welcome back",
        "auth.create.account": "Create an account",
        "auth.login.desc": "Enter your credentials to access your account",
        "auth.register.desc": "Enter your details to create your account",
        "auth.name": "Name",
        "auth.email": "Email address",
        "auth.password": "Password",
        "auth.submit.login": "Sign in",
        "auth.submit.register": "Sign up",
        "auth.switch.toRegister": "Don't have an account? Sign up",
        "auth.switch.toLogin": "Already have an account? Sign in",
        "auth.error.default": "Authentication failed",
        "auth.error.missing": "Please fill in all fields",

        // Mind Maps
        "mindmap": "Mind Map",
        "nav.mindmaps": "Mind Maps",
        "mindmap.title": "Mind Maps",
        "mindmap.subtitle": "Visualize your knowledge with AI-generated diagrams.",
        "mindmap.new": "New Mind Map",
        "mindmap.search": "Search mind maps...",
        "mindmap.empty.title": "No mind maps yet",
        "mindmap.empty.desc": "Create your first mind map from your notes to better visualize concepts and connections.",
        "mindmap.empty.action": "Create Now",
        "mindmap.sources": "sources",
        "mindmap.open": "Open",
        "mindmap.delete.confirm": "Are you sure you want to delete this mind map?",
        // Generation Modal
        "mindmap.gen.title": "Generate AI Mind Map",
        "mindmap.gen.name": "Mind Map Name (Optional)",
        "mindmap.gen.name.placeholder": "e.g., History of Rome Overview",
        "mindmap.gen.notes.label": "Select Notes to Analyze",
        "mindmap.gen.notes.placeholder": "Search your notes...",
        "mindmap.gen.file.label": "Select Files to Analyze",
        "mindmap.gen.file.placeholder": "Search your files (PDF, DOCX)...",
        "mindmap.gen.doc.selected": "Selected Document",
        "mindmap.gen.upload.label": "Upload PDF/DOCX (Coming Soon)",
        "mindmap.gen.cancel": "Cancel",
        "mindmap.gen.submit": "Generate Mind Map",
        "mindmap.gen.generating": "Generating...",
        "mindmap.gen.success": "Mind Map generated successfully!",
        "mindmap.gen.error": "Failed to generate mind map",
        "ai.model.label": "Select AI Model"
    },
    fr: {
        "app.title": "EduTrack",
        "nav.myCourses": "Mes Cours",
        "nav.noCourses": "Aucun cours pour le moment.",
        "nav.newCourse": "Nouveau Cours",
        "nav.library": "Bibliothèque",
        "nav.settings": "Paramètres",
        "nav.selectProfile": "Veuillez d'abord sélectionner un profil.",
        "course.create.title": "Créer un nouveau cours",
        "course.create.name": "Titre du cours",
        "course.create.desc": "Description (Optionnel)",
        "course.create.color": "Couleur",
        "course.create.cancel": "Annuler",
        "course.create.submit": "Créer le cours",
        "course.create.loading": "Création...",
        "course.move.success": "Cours déplacé avec succès",
        "course.delete.confirm": "Êtes-vous sûr de vouloir supprimer ce cours ? Tout le contenu sera perdu.",
        "item.delete.confirm": "Voulez-vous vraiment supprimer cet élément ?",
        "course.notFound": "Cours introuvable ou chargement...",
        "course.addContent": "Ajouter du contenu",
        "course.tabs.all": "Tout",
        "course.tabs.exercises": "Exercices",
        "course.tabs.notes": "Notes",
        "course.tabs.resources": "Ressources",
        "course.empty": "Aucun élément trouvé dans cette section.",
        "course.search": "Rechercher...",
        "item.create.title": "Ajouter du contenu",
        "item.create.type.note": "Note",
        "item.create.type.exercise": "Exercice",
        "item.create.type.resource": "Ressource",
        "item.form.title": "Titre",
        "item.form.title.placeholder.note": "ex: Résumé de cours",
        "item.form.title.placeholder.exercise": "ex: TD Analyse 1",
        "item.form.title.placeholder.resource": "ex: Manuel PDF",
        "item.form.content": "Contenu",
        "item.form.status": "Statut",
        "item.form.difficulty": "Difficulté",
        "item.edit.error": "Erreur lors de la mise à jour",
        "item.edit.save": "Enregistrer",
        "item.edit.save_loading": "Enregistrement...",
        "item.edit.drop_file": "Déposez le fichier ici",
        "common.optional": "Optionnel",
        "item.form.desc": "Description",
        "item.form.file": "Fichier",
        "item.form.file.placeholder": "Cliquez ou glissez un fichier ici",
        "item.form.file.supports": "Supporte PDF, Images, ZIP",
        "item.form.submit.note": "Créer la Note",
        "item.form.submit.exercise": "Créer l'Exercice",
        "item.form.submit.resource": "Ajouter la Ressource",
        "item.noContent": "Aucun contenu à afficher.",
        "item.startWriting": "Commencer à écrire",
        "status.todo": "À faire",
        "status.in-progress": "En cours",
        "status.completed": "Terminé",
        "diff.easy": "Facile",
        "diff.medium": "Moyen",
        "diff.hard": "Difficile",
        "lang.toggle": " Langue",
        "welcome.empty.title": "Commencez votre apprentissage",
        "welcome.empty.desc": "Créez votre premier cours pour commencer à suivre vos progrès.",
        "welcome.create.button": "Créer mon premier cours",
        "welcome.title": "Bon retour !",
        "welcome.subtitle": "Sélectionnez un cours pour commencer.",
        "welcome.card.title": "Pour commencer",
        "welcome.card.desc": "Créez votre premier cours via la barre latérale.",
        "profiles.manager.title": "Gérer les Profils",
        "profiles.dropdown.select": "Sélect. Profil",
        "profiles.dropdown.switch": "Changer de Profil",
        "profiles.dropdown.add": "Ajouter un Profil",
        "profiles.dropdown.manage": "Gérer les Profils",
        "profiles.dropdown.logout": "Déconnexion (Fermer)",
        "dashboard.stats.courses": "Cours",
        "dashboard.stats.exercises": "Exercices",
        "dashboard.stats.notes": "Notes",
        "dashboard.stats.aiGeneration": "Génération IA",
        "dashboard.recent": "Cours Récents",
        "dashboard.inprogress": "En Cours",
        "dashboard.activity": "Journal d'Activité",
        "dashboard.empty.courses": "Aucun cours pour l'instant.",
        "dashboard.empty.activity": "Aucune activité récente.",
        "changelog.title": "Nouveautés",
        "changelog.view": "Voir les changements",
        "changelog.desc": "Consultez l'historique des mises à jour.",
        "drop.title": "Lâchez le fichier pour uploader",
        "folder.new": "Nouveau Sujet",
        "folder.create.sub": "Nouveau Sous-Dossier",
        "folder.create.prompt": "Entrez le nom du dossier :",
        "folder.delete.confirm": "Supprimer ce dossier ? Le contenu remontera au parent.",
        "settings.title": "Paramètres du Cours",
        "action.delete": "Supprimer",
        "action.cancel": "Annuler",
        "action.close": "Fermer",
        "action.openNewTab": "Ouvrir dans un nouvel onglet",
        "action.fullscreen": "Plein écran (Local)",
        "action.zoomOut": "Dézoomer",
        "action.zoomIn": "Zoomer",
        "action.rotate": "Pivoter",
        "action.expand": "Agrandir",
        "action.download": "Télécharger",
        "action.copy": "Copier dans le presse-papiers",
        "action.summarize": "Résumer",
        "action.preview": "Aperçu",
        "action.refresh": "Actualiser",
        "export.pdf": "Exporter en PDF",
        "export.word": "Exporter en Word",
        "export.anki": "Exporter Anki",
        "document.fullscreen": "Document en plein écran",
        "document.pdf": "Document PDF",
        "document.viewer": "Visionneuse de document",
        "office.switchViewer": "Changer de lecteur si l'affichage bug",
        "profile.delete.tooltip": "Supprimer le profil",
        "sidebar.expandTimer": "Développer pour voir le minuteur",
        "timer.reset": "Réinitialiser le minuteur",
        "theme.toggle": "Changer de thème",
        "calendar.autoDetect": "Détection auto depuis Google Calendar",
        "file.thumbnail": "Miniature du fichier",
        "icon.none": "Aucune icône",
        // Search
        "search.placeholder": "Chercher cours, notes, exercices...",
        "search.noResults": "Aucun résultat pour",
        "search.type": "Tapez pour chercher...",
        "search.searching": "Recherche en cours...",
        "search.results": "résultats",
        "search.nav": "naviguer",
        "ai.model.label": "Modèle IA",
        "search.select": "sélectionner",
        // Summary
        "summary.title": "Options de Résumé",
        "summary.compression": "Compression",
        "summary.format": "Format",
        "summary.preserveHeadings": "Garder les titres",
        "summary.detectKeywords": "Détecter Mots-clés (Dates, Formules)",
        "summary.useWebSearch": "Recherche Web Contextuelle (Perplexity)",
        "summary.desc.20": "Ultra-court. Définitions & formules clés seulement.",
        "summary.desc.40": "Équilibré. Recommandé pour l'étude.",
        "summary.desc.50": "Détaillé. Inclut exemples et contexte.",
        "summary.generate": "Générer Résumé",
        "summary.generated": "Résumé Généré",
        "summary.copy": "Copier",
        "summary.regenerate": "Régénérer",
        "summary.configure": "Configurer",
        "summary.view": "Voir Résumé",
        "summary.hide": "Masquer Résumé",
        "summary.trigger": "Résumer",
        "summary.stats.words": "Mots",
        "summary.stats.ratio": "Ratio",
        "summary.stats.time": "Temps",
        "summary.error.noContent": "Aucun contenu texte trouvé pour le résumé. Les fichiers PDF/Images ne sont pas encore supportés.",
        "summary.fmt.bullets": "Puces",
        "summary.fmt.paragraph": "Paragraphe",
        "summary.fmt.outline": "Plan",
        "summary.fmt.timeline": "Chronologie",
        "summary.provider": "Modèle de Génération",
        "summary.error.ai": "Échec de l'IA. Vérifiez vos clés d'API.",
        // Common / Folder
        "common.folder": "Dossier",
        "common.save": "Enregistrer",
        "common.saving": "Enregistrement...",
        "common.noDesc": "Aucune description",
        "folder.empty": "Ce dossier est vide.",
        "calendar.noEvents": "Aucun événement",
        "calendar.allDay": "Toute la journée",
        "calendar.synced": "Synchronisé",
        "calendar.connected": "Connecté",
        "calendar.connect": "Connecter Agenda",
        "calendar.connecting": "Connexion...",
        "app.search": "Rechercher...",
        "board.caseFile": "DOSSIER",
        "board.note": "NOTE",
        "board.evidence": "PREUVE",
        "board.exercise": "EXERCICE",
        "board.search.placeholder": "Rechercher...",
        "board.type": "Type : ",
        "board.doubleClickOpen": "Double-cliquer pour ouvrir",
        "board.containsItems": "Contient {{count}} éléments",
        "board.document": "Document",
        "board.upload": "Déposer des fichiers",
        "board.assign": "Assigner",
        "board.mapTitle": "Tableau d'Enquête",
        "board.orphans": "Cours Non Classés",
        "board.noOrphans": "Aucun cours orphelin.",
        "common.topics": "Sujets",
        "common.courses": "Cours",
        "common.documents": "Documents",
        "action.filter": "Filtres",
        "action.fitView": "Ajuster la vue",
        "action.resetLayout": "Réinitialiser",
        "action.export": "Exporter",
        "action.assign": "Assigner",
        "action.upload": "Uploader",
        "action.enterZen": "Mode Zen",
        "action.exitZen": "Quitter Zen",
        "nav.board": "Tableau d'Enquête",
        "board.mode": "Mode Détective",
        "profile.create.name.placeholder": "ex: Jean Dupont",
        "profile.create.email.placeholder": "jean@exemple.com",
        "settings.api.placeholder.pplx": "pplx-...",
        "settings.api.placeholder.gemini": "AIza...",
        "settings.api.placeholder.bearer": "Bearer ...",
        "course.create.name.placeholder": "ex: Analyse Avancée",
        "course.create.desc.placeholder": "Bref résumé du cours...",
        "item.form.instructions.placeholder": "Instructions pour l'exercice...",
        // Item Edit
        "item.edit": "Modifier",
        "item.edit.title": "Modifier l'élément",
        "item.edit.replaceFile": "Remplacer le fichier",
        "item.edit.keepFile": "Conserver le fichier actuel",
        "item.edit.success": "Élément mis à jour avec succès",
        // New Additions
        "focus.enter": "Mode Concentration",
        "focus.exit": "Quitter Focus",
        "focus.enter.tooltip": "Entrer en Mode Concentration",
        "focus.exit.tooltip": "Quitter le mode concentration (Echap)",
        "focus.mode": "Mode Focus",
        "focus.work": "Concentration",
        "focus.shortBreak": "Pause Courte",
        "focus.longBreak": "Pause Longue",
        "focus.current": "Focus Actuel",
        "focus.ready": "Prêt",
        "focus.active": "En Cours",
        "action.pause": "Pause",
        "action.start": "Démarrer",
        "summary.generating": "Rédaction du résumé académique en cours...",
        "summary.error.display": "Erreur d'affichage du résumé.",
        "file.unknownSize": "Taille inconnue",
        "file.attached": "Fichier Joint",
        "file.download": "Télécharger",
        "course.return": "Retour au Cours",
        "export.defaultTitle": "Résumé",
        "export.generatedOn": "Généré le :",
        "export.contentComplex": "Contenu complexe",
        "bulk.selected_singular": "Élément sélectionné",
        "bulk.selected_plural": "Éléments sélectionnés",
        "bulk.generate": "Génération",
        "bulk.generate.flashcards": "Flashcards",
        "bulk.generate.quiz": "Quiz",
        "bulk.generate.summary": "Résumé",
        "common.delete": "Supprimer",
        "common.cancel": "Annuler",
        "common.back": "Retour",
        // Settings Page
        "settings.page.title": "Paramètres",
        "settings.page.subtitle": "Gérez vos préférences et configurations globales.",
        "settings.tabs.api": "Clés API & Services",
        "settings.tabs.appearance": "Apparence",
        "settings.tabs.shortcuts": "Raccourcis Clavier",
        "settings.api.title": "Configuration des Services",
        "settings.api.desc": "Configurez vos clés d'API pour les services d'IA et les intégrations.",
        "settings.appearance.title": "Apparence",
        "settings.appearance.desc": "Personnalisez le look de votre application.",
        "settings.shortcuts.title": "Raccourcis Clavier",
        "settings.shortcuts.desc": "Maîtrisez l'application avec les commandes rapides.",
        "settings.shortcuts.global": "Navigation Globale",
        "settings.shortcuts.flashcards": "Flashcards",
        "settings.theme.light": "Clair",
        "settings.theme.dark": "Sombre",
        "settings.theme.system": "Système",

        // Trier & Vue
        'sort.by': 'Trier par',
        'sort.label': 'Trier par',
        'sort.alpha': 'Ordre alphabétique',
        'sort.alphabetical': 'Ordre alphabétique',
        'sort.date': 'Date d\'ajout',
        'sort.dateAdded': 'Date d\'ajout',
        'sort.last_opened': 'Dernière ouverture',
        'sort.lastOpened': 'Dernière ouverture',
        'view.grid': 'Grille',
        'view.list': 'Liste',
        'action.selectAll': 'Tout sélectionner',
        'grid.columns': 'Colonnes',
        "settings.save.button": "Sauvegarder les clés",
        "settings.save.saving": "Sauvegarde...",
        "settings.save.success": "Clés API sauvegardées avec succès !",
        "settings.save.error": "Erreur lors de la sauvegarde.",
        "settings.api.perplexity.default": "Perplexity AI (Par défaut)",
        "settings.api.perplexity.summaries": "Perplexity - Résumés",
        "settings.api.perplexity.exercises": "Perplexity - Exercices",
        "settings.api.gemini.vincent": "Google Gemini (Vincent Pena)",
        "settings.api.gemini.summaries": "Google Gemini - Résumés",
        "settings.api.gemini.exercises": "Google Gemini - Exercices",
        "settings.api.integrations": "Intégrations",
        "settings.api.calendar": "Autorisation Google Calendar",
        // Generation Menu
        "gen.menu.button": "Génération",
        "gen.menu.title": "Générer du contenu",
        "gen.flashcards.title": "Flashcards",
        "gen.flashcards.desc": "Cartes mémoire pour la mémorisation espacée.",
        "gen.quiz.title": "QCM Intelligent",
        "gen.quiz.desc": "Questions à choix multiples pour tester vos connaissances.",
        "gen.plan.title": "Plan de Révision",
        "gen.plan.desc": "Planning hebdomadaire généré par IA.",
        "gen.viewAll": "Voir tous mes exercices",
        "gen.empty": "Aucun excercice généré",
        "gen.start": "Utilisez le bouton Génération pour commencer.",
        "gen.list.cards": "cartes",
        "gen.list.questions": "Questions",
        "gen.list.mastery": "Maîtrise",
        "gen.action.start": "Commencer",
        "gen.action.quiz": "Passer le Quiz",
        "gen.delete.confirm": "Voulez-vous vraiment supprimer cet exercice ?",
        "gen.delete.error": "Erreur lors de la suppression",
        "common.open": "Ouvrir",
        "common.in": "dans",

        // TTS (FR)
        "tts.play": "Lire à voix haute",
        "tts.pause": "Pause",
        "tts.resume": "Reprendre",
        "tts.stop": "Arrêter",
        "tts.speed": "Vitesse",
        "tts.unsupported": "La synthèse vocale n'est pas supportée par votre navigateur",
        "tts.error": "Échec de la lecture",
        "tts.reading": "Lecture en cours...",

        // STT (FR)
        "stt.start": "Démarrer la dictée",
        "stt.stop": "Arrêter la dictée",
        "stt.listening": "J'écoute...",
        "stt.unsupported": "Reconnaissance vocale non supportée",
        "stt.error.permission": "Accès Micro Refusé",
        "stt.error.https": "La reconnaissance vocale nécessite une connexion sécurisée HTTPS (ou localhost).",
        "stt.error.blocked": "Veuillez autoriser l'accès au micro dans les paramètres du navigateur.",
        "stt.error.generic": "Échec de la reconnaissance vocale.",

        "changelog.v051.title": "Mobilité & Stabilité 📱⚡",
        "changelog.v051.mobile": "Optimisation Mobile : Refonte de la vue cours, aperçus de fichiers plus fluides et en-tête intelligent pour smartphones.",
        "changelog.v051.folders": "Navigation : Dossiers ouverts par défaut et amélioration de la visibilité de la hiérarchie.",
        "changelog.v051.office": "Lecteur Office : Intégration de Google Docs Viewer pour une lecture fiable des PPT et Excel.",
        "changelog.v051.api": "Sabilité : Correction des sessions expirées, de l'intercepteur API et des erreurs de dépendances critiques.",
        "changelog.v052.title": "Productivité & Révisions 🚀",
        "changelog.v052.revision": "Plan de Révision IA : Générez votre planning d'études personnalisé en un clic.",
        "changelog.v052.edit": "Édition Rapide : Modifiez vos items et remplacez les fichiers sans tout recréer.",
        "changelog.v052.vscode": "VS Code Sync : Ouvrez vos projets de code directement dans VS Code depuis l'app.",
        "changelog.v052.pptx": "Support Office Web : Aperçu des PPTX/DOCX maintenant compatible via Google/Microsoft Viewers.",
        "changelog.v052.ui": "UI Fixes : Améliorations visuelles (centrage menus, bordures).",
        "changelog.v053.title": "Performance & Vitesse ⚡",
        "changelog.v053.perf": "PageSpeed : Score augmenté de 53 à 90+.",
        "changelog.v053.cache": "Cache Intelligent : Les ressources sont en cache pour une navigation instantanée.",
        "changelog.v053.lazy": "Lazy Loading : Chargement initial accéléré grâce au découpage du code.",
        "changelog.v053.images": "Assets Optimisés : Images compressées et décodées en asynchrone.",

        // v0.5.8
        "changelog.v058.title": "Voix & Accessibilité 🗣️",
        "changelog.v058.tts": "Synthèse Vocale : Écoutez vos notes avec contrôle de vitesse et détection de langue.",
        "changelog.v058.stt": "Reconnaissance Vocale : Dictez votre contenu directement dans l'éditeur.",
        "changelog.v058.library": "Bibliothèque : Un espace dédié pour explorer et filtrer tous vos cours.",
        "changelog.v058.dashboard": "Tableau de Bord : Mise en page améliorée et minuteur focus compact dans l'en-tête.",

        // v0.5.9
        "changelog.v059.title": "Focus & Esthétique 🎨",
        "changelog.v059.analytics": "Analytics de Focus : Enregistrement des sessions et visualisation graphique de votre productivité.",
        "changelog.v059.themes": "Thèmes Personnalisés : Ajout des nouveaux thèmes 'Nature' et 'Sunset' pour une expérience sur mesure.",
        "changelog.v059.dashboard": "Mode Clair Dashboard : Refonte du Dashboard pour un support complet du thème clair.",
        "changelog.v059.notes": "Style des Notes : Amélioration visuelle et uniformisation du rendu des notes avec l'éditeur.",

        // v1.3.0
        "changelog.v130.title": "Performance & Mobile 🚀",
        "changelog.v130.mobile": "Expérience Mobile : Visualiseur de ressources redessiné avec support plein écran et boutons optimisés.",
        "changelog.v130.performance": "Ultra-Rapide : Temps de chargement réduits de 40% grâce au découpage intelligent du code et aux ressources optimisées.",
        "changelog.v130.documents": "Correction Import : Vous pouvez maintenant joindre des fichiers aux exercices sans erreur.",
        "changelog.v130.ai": "IA Mise à Jour : Nouveaux modèles Gemini 2.5 avec fiabilité améliorée.",

        // v0.5.4
        "changelog.v054.title": "Mise à jour Power User",
        "changelog.v054.board": "Nouveau Tableau d'Enquête pour visualiser vos connaissances.",
        "changelog.v054.command": "Centre de Commande Global (Ctrl+K) pour tout contrôler.",
        "changelog.v054.focus": "Mode Focus ajouté avec Timer Pomodoro intégré.",
        "changelog.v054.sidebar": "Barre latérale rétractable pour plus d'espace.",
        // v0.5.5
        "changelog.v055.title": "Tableau d'Enquête - Complet",
        "changelog.v055.board_complete": "Phase 3 : Recherche, filtres et mini-carte pour naviguer efficacement.",
        "changelog.v055.drag_drop": "Glisser-déposer : Assignez les cours orphelins aux sujets via drag & drop.",
        "changelog.v055.filters": "Filtres avancés (Sujets, Cours) pour une meilleure organisation.",
        "changelog.v055.layout": "Algorithme de disposition radiale amélioré et positionnement des nœuds.",
        // v0.5.6
        "changelog.v056.title": "Intégration des Documents",
        "changelog.v056.documents": "Les documents (PDF, Images, fichiers Office) apparaissent maintenant sur le tableau.",
        "changelog.v056.filters": "Ajout du filtre Documents pour afficher/masquer les items.",
        // v0.5.7
        "changelog.v057.title": "Améliorations Visuelles",
        "changelog.v057.cork": "Texture liège améliorée avec motif CSS.",
        "changelog.v057.pins": "Ajout de punaises colorées sur tous les nœuds (Rouge : Sujets, Jaune : Cours, Bleu : Documents).",
        "changelog.v057.documents_fix": "Correction du bug de rendu du filtre documents.",
        "changelog.v057.reset_view": "La vue réinitialisée se centre maintenant intelligemment sur le contenu.",
        // v0.5.0
        "changelog.v050.title": "Stabilité & Intelligence 🧠",
        "changelog.v050.api_keys": "Persistance Clés API : Correction d'un bug critique où les clés disparaissaient.",
        "changelog.v050.logout": "Déconnexion Propre : Le bouton 'Déconnexion' nettoie maintenant correctement la session.",
        "changelog.v050.ai_reliability": "Fiabilité IA : Correction des erreurs 404/500 et meilleure gestion des quotas Gemini.",
        "changelog.v050.polish": "Polissage Localisation : Traductions françaises corrigées et thème 'Minecraft' partout.",
        "changelog.v041.title": "Hub de Ressources 📂",
        "changelog.v041.viewer": "Visionneuse Multi-Format : Support natif des PDF, documents Office (Word, Excel, PowerPoint) et images directement dans l'app.",
        "changelog.v041.metadata": "Métadonnées : Cartes de ressources plus claires affichant format, date et nom complet.",
        "changelog.v041.delete_fix": "Suppression Sécurisée : Correction des erreurs 'Fichier non trouvé' et ajout de feedback visuel.",
        "changelog.v041.doc_type": "Détection Doc : Détection robuste du type de fichier assurant l'ouverture dans la bonne visionneuse.",
        "changelog.v040.title": "Refonte Synchro Cloud 🔄",
        "changelog.v040.infra": "Infrastructure Sync : Backend de synchronisation entièrement refait pour corriger l'authentification.",
        "changelog.v040.upload": "Upload Fichiers : Résolution des erreurs 404 (Nginx).",
        "changelog.v040.schema": "Schéma Base de Données : Correction génération UUID pour dossiers et cours.",
        "changelog.v040.speed": "Vitesse Sync : Intervalle réduit de 30s à 3s pour des mises à jour quasi-instantanées.",
        "changelog.v040.cleanup": "Nettoyage Intelligent : Suppression auto des vieux enregistrements (>7 jours).",
        "changelog.v040.tombstone": "Optimisation Tombstone : Synchro des suppressions sur 24h seulement.",
        "changelog.v040.nginx": "Config Nginx : Correction du routage API (/api/, /auth/, /sync).",
        "changelog.v030.title": "Focus & Localisation 🌍",
        "changelog.v030.focus": "Mode Focus : Résumés en plein écran sans distraction.",
        "changelog.v030.multilang": "Multi-Langue : Disponible en Anglais, Français et... Minecraft ?",
        "changelog.v030.ai2": "Résumés IA 2.0 : Utilise Gemini pour des résumés plus pertinents.",
        "changelog.v030.export": "Export Amélioré : Téléchargement en PDF et Word (.docx).",
        "changelog.v020.title": "Export PDF & Recherche",
        "changelog.v020.pdf": "Export PDF : Génération de PDF professionnels pour vos résumés.",
        "changelog.v020.command": "Centre de Commande : `Cmd+K` pour tout rechercher instantanément.",
        "changelog.v020.analytics": "Analytics : Timeline d'activité.",
        "changelog.v020.large_files": "Optimisation gros fichiers.",
        "changelog.v015.title": "Structure & Organisation",
        "changelog.v015.recursive": "Dossiers Récursifs : Arborescence infinie.",
        "changelog.v015.favorites": "Favoris Rapides : Épinglez vos cours importants.",
        "changelog.v015.dnd": "Drag & Drop : Réorganisation intuitive.",
        "changelog.v010.title": "Genèse",
        "changelog.v010.engine": "Moteur d'Apprentissage : Cours, Notes, Exercices.",
        "changelog.v010.graph": "Graphe de Connaissances : Visualisation interactive.",
        "changelog.current": "ACTUEL",
        // Revision Program
        "revision.program": "Programme de Révision",
        "revision.generate": "Générer le Programme",
        "revision.selectTarget": "Sélectionner un Cours ou Dossier",
        "revision.examDate": "Date de l'Examen",
        "revision.noCalendar": "Aucun calendrier lié",
        "revision.linkCalendar": "Lier un Calendrier",
        "revision.availableTime": "Temps Disponible",
        "revision.hours": "Heures",
        "revision.days": "Jours",
        "revision.generating": "Génération de votre plan d'étude personnalisé...",
        "plan.calendar.notConnected": "Connectez d'abord votre calendrier Google via le bouton en haut.",
        "plan.calendar.found": "Examen trouvé : {event} le {date}",
        "plan.calendar.notFound": "Aucun événement trouvé pour '{course}'",
        "plan.calendar.error": "Erreur de synchronisation calendrier.",
        "plan.error.noDeadline": "Veuillez sélectionner une date d'examen.",
        "plan.success": "Programme de révision généré avec succès !",
        "plan.error.failed": "Échec de la génération. Veuillez réessayer.",
        // Auth
        "auth.welcome.back": "Bon retour",
        "auth.create.account": "Créer un compte",
        "auth.login.desc": "Entrez vos identifiants pour accéder à votre compte",
        "auth.register.desc": "Entrez vos coordonnées pour créer votre compte",
        "auth.name": "Nom",
        "auth.email": "Adresse Email",
        "auth.password": "Mot de passe",
        "auth.submit.login": "Se connecter",
        "auth.submit.register": "S'inscrire",
        "auth.switch.toRegister": "Pas de compte ? S'inscrire",
        "auth.switch.toLogin": "Déjà un compte ? Se connecter",
        "auth.error.default": "Échec de l'authentification",
        "auth.error.missing": "Veuillez remplir tous les champs",
        "board.subtitle": "Explorez votre base de connaissances",
        "nav.explore": "Explorer",

        // Mind Maps (FR)
        "mindmap": "Mind Map",
        "nav.mindmaps": "Mind Maps",
        "mindmap.title": "Mind Maps",
        "mindmap.subtitle": "Visualisez vos connaissances avec des diagrammes générés par IA.",
        "mindmap.new": "Nouveau Mind Map",
        "mindmap.search": "Rechercher...",
        "mindmap.empty.title": "Aucun mind map pour l'instant",
        "mindmap.empty.desc": "Créez votre premier mind map à partir de vos notes pour mieux visualiser les concepts.",
        "mindmap.empty.action": "Créer",
        "mindmap.sources": "sources",
        "mindmap.open": "Ouvrir",
        "mindmap.delete.confirm": "Êtes-vous sûr de vouloir supprimer ce mind map ?",
        // Generation Modal
        "mindmap.gen.title": "Générer Mind Map IA",
        "mindmap.gen.name": "Nom du Mind Map (Optionnel)",
        "mindmap.gen.name.placeholder": "ex: Aperçu Histoire de Rome",
        "mindmap.gen.notes.label": "Sélectionner Notes à Analyser",
        "mindmap.gen.notes.placeholder": "Chercher vos notes...",
        "mindmap.gen.file.label": "Sélectionner Fichiers à Analyser",
        "mindmap.gen.file.placeholder": "Chercher vos fichiers (PDF, DOCX)...",
        "mindmap.gen.doc.selected": "Document Sélectionné",
        "mindmap.gen.upload.label": "Upload PDF/DOCX (Bientôt)",
        "mindmap.gen.cancel": "Annuler",
        "mindmap.gen.submit": "Générer Mind Map",
        "mindmap.gen.generating": "Génération...",
        "mindmap.gen.success": "Mind Map généré avec succès !",
        "mindmap.gen.error": "Échec de la génération"
    },
    mc: {
        "app.title": "EduCraft",
        "nav.myCourses": "My Worlds",
        "nav.noCourses": "No worlds generated yet.",
        "nav.newCourse": "New World",
        "nav.library": "Archives",
        "nav.settings": "Server Props",
        "nav.selectProfile": "Choose a character first!",
        "dashboard.stats.courses": "Worlds",
        "dashboard.stats.exercises": "Quests",
        "dashboard.stats.notes": "Books",
        "dashboard.stats.aiGeneration": "Command Blocks",
        "dashboard.recent": "Recent Worlds",
        "dashboard.inprogress": "Raiding",
        "dashboard.activity": "Server Logs",
        "dashboard.empty.courses": "No worlds yet.",
        "dashboard.empty.activity": "No logs.",
        "changelog.title": "Patch Notes",
        "changelog.view": "Read Patch Notes",
        "changelog.desc": "Check the server version history.",
        "course.create.title": "Generate New World",
        "course.create.name": "World Name",
        "course.create.desc": "Seed Info / Biome Data",
        "course.create.color": "Dye Color",
        "course.create.cancel": "Respawn",
        "course.create.submit": "Craft World",
        "course.create.loading": "Generating chunks...",
        "course.delete.confirm": "Are you sure you want to drop this item into lava? All data will be lost.",
        "item.delete.confirm": "Throw this item into cactus?",
        "course.notFound": "Chunks not loaded...",
        "course.addContent": "Craft Item",
        "course.tabs.all": "Inventory",
        "course.tabs.exercises": "Quests",
        "course.tabs.notes": "Books",
        "course.tabs.resources": "Loot",
        "course.empty": "Inventory empty.",
        "item.noContent": "Empty chest.",
        "item.startWriting": "Scribe in Book",
        "course.search": "Locate item...",
        "item.create.title": "Crafting Table",
        "item.create.type.note": "Book & Quill",
        "item.create.type.exercise": "Quest",
        "item.create.type.resource": "Map",
        "item.form.title": "Item Name",
        "item.form.title.placeholder.note": "e.g. Book of Spells",
        "item.form.title.placeholder.exercise": "e.g. Ender Dragon Raid",
        "item.form.title.placeholder.resource": "e.g. Biome Map",
        "item.form.content": "Pages / Data",
        "item.form.status": "Quest State",
        "item.form.difficulty": "Mob Level",
        "item.form.desc": "Lore",
        "item.form.file": "Schematic",
        "item.form.file.placeholder": "Drop item stack here",
        "item.form.file.supports": "Supports Maps, Paintings",
        "item.form.submit.note": "Sign Book",
        "item.form.submit.exercise": "Start Quest",
        "item.form.submit.resource": "Store in Chest",
        "status.todo": "Spawned",
        "status.in-progress": "Raiding",
        "status.completed": "Defeated",
        "diff.easy": "Peaceful",
        "diff.medium": "Normal",
        "diff.hard": "Hardcore",
        "theme.toggle": "Toggle Day/Night",
        "lang.toggle": "Language",
        "welcome.title": "Reviewing Server",
        "welcome.subtitle": "Select a world to teleport to.",
        "welcome.card.title": "Spawn Point",
        "welcome.card.desc": "Generate a new world in the sidebar.",
        "profiles.manager.title": "World Ops",
        "profiles.dropdown.select": "Select Entity",
        "profiles.dropdown.switch": "Switch Dimension",
        "profiles.dropdown.add": "Spawn Guest",
        "profiles.dropdown.manage": "Server Settings",
        "profiles.dropdown.logout": "Quit Game (Close)",
        "drop.title": "Drop stack to upload",
        "folder.new": "New Biome",
        "folder.create.sub": "New Chunk",
        "folder.create.prompt": "Name this region:",
        "folder.delete.confirm": "Destroy this biome? Mobs will migrate to neighbor.",
        "settings.title": "World Options",
        "action.delete": "Destroy Block",
        "action.cancel": "Sneak",
        "action.close": "Quit Menu",
        "action.openNewTab": "Launch External Portal",
        "action.fullscreen": "Maximize View",
        "action.zoomOut": "Shrink",
        "action.zoomIn": "Enlarge",
        "action.rotate": "Spin",
        "action.expand": "Grow",
        "action.download": "Loot",
        "action.copy": "Duplicate to Inventory",
        "action.upload": "Craft Item",
        "action.enterZen": "Hide HUD",
        "action.exitZen": "Show HUD",
        "action.summarize": "Condense",
        "action.preview": "Peek",
        "action.refresh": "Reload Chunks",
        "export.pdf": "Craft PDF Scroll",
        "export.word": "Craft Word Book",
        "document.fullscreen": "Full Canvas View",
        "document.pdf": "Scroll Document",
        "document.viewer": "Book Reader",
        "office.switchViewer": "Try different viewer",
        "profile.delete.tooltip": "Remove Player",
        "sidebar.expandTimer": "Show Time Crystal",
        "timer.reset": "Reset Hourglass",

        "calendar.autoDetect": "Detect from Sundial",
        "file.thumbnail": "Item Preview",
        "icon.none": "No Symbol",
        "app.search": "Locate...",
        "profile.create.name.placeholder": "e.g. Steve",
        "profile.create.email.placeholder": "steve@minecraft.net",
        "settings.api.placeholder.pplx": "pplx-...",
        "settings.api.placeholder.gemini": "AIza...",
        "settings.api.placeholder.bearer": "Bearer ...",
        "course.create.name.placeholder": "e.g. Survival World",
        "course.create.desc.placeholder": "Seed info...",
        "item.form.instructions.placeholder": "Quest details...",
        "calendar.noEvents": "No raids planned",
        "calendar.allDay": "Sun to Moon",
        "calendar.synced": "Map Updated",
        "calendar.connected": "Portal Linked",
        "calendar.connect": "Link Portal",
        "calendar.connecting": "Linking...",
        // Search
        "search.placeholder": "Locate intentory items...",
        "search.noResults": "No entities found for",
        "search.type": "Use /locate...",
        "search.searching": "Chunk loading...",
        "search.results": "entities",
        "search.nav": "fly",
        "search.select": "interact",
        // Summary
        "summary.title": "Enchantment Table Options",
        "summary.compression": "Simplification Level",
        "summary.format": "Scroll Format",
        "summary.preserveHeadings": "Keep Runes",
        "summary.detectKeywords": "Detect Spells (Formulas)",
        "summary.desc.20": "Level 1. Basic runes only.",
        "summary.desc.40": "Level 30. Balanced enchant.",
        "summary.desc.50": "God Roll. Max info.",
        "summary.generate": "Enchant Item",
        "summary.generated": "Enchanted Scroll",
        "summary.copy": "Copy to Chat",
        "summary.regenerate": "Re-roll Enchant",
        "summary.configure": "Anvil",
        "summary.view": "Read Scroll",
        "summary.hide": "Close Scroll",
        "summary.trigger": "Enchant",
        "summary.stats.words": "Runes",
        "summary.stats.ratio": "Power",
        "summary.stats.time": "Ticks",
        "summary.error.noContent": "The scroll is blank! No readable runes found. (PDFs not supported)",
        "summary.fmt.bullets": "List",
        "summary.fmt.paragraph": "Book",
        "summary.fmt.outline": "Map",
        "summary.fmt.timeline": "History",
        "summary.provider": "Enchantment Source",
        "summary.error.ai": "The scroll failed to enchant! Check your Redstone.",
        "common.back": "Turn Back",
        // Common / Folder
        "common.folder": "Biome",
        "common.noDesc": "No Lore",
        "folder.empty": "Void biome.",
        // New Additions
        "focus.enter": "Focus Beacon",
        "focus.exit": "Leave Beacon Range",
        "focus.enter.tooltip": "Activate Focus Beacon",
        "focus.exit.tooltip": "Deactivate Beacon (Esc)",
        "focus.mode": "Beacon Mode",
        "focus.work": "Mining",
        "focus.shortBreak": "Eat Bread",
        "focus.longBreak": "Sleep",
        "focus.current": "Current Quest",
        "focus.ready": "Spawned",
        "focus.active": "Raiding",
        "action.pause": "AFK",
        "action.start": "Go!",
        "summary.generating": "Scribing enchantment in progress...",
        "summary.error.display": "The scroll is cursed/unreadable.",
        "file.unknownSize": "Unknown weight",
        "file.attached": "Attached Loot",
        "file.download": "Pick Block",
        "course.return": "Teleport to World",
        "export.defaultTitle": "Enchanted_Scroll",
        "export.generatedOn": "Crafted on:",
        "export.contentComplex": "NBT Data",
        // Settings Page
        "settings.page.title": "Server Properties",
        "settings.page.subtitle": "Configure game rules and world settings.",
        "settings.tabs.api": "Command Blocks & API",
        "settings.tabs.appearance": "Resource Packs",
        "settings.tabs.shortcuts": "Keybinds",
        "settings.api.title": "Redstone Circuits",
        "settings.api.desc": "Link your command blocks to external servers.",
        "settings.appearance.title": "Resource Packs",
        "settings.appearance.desc": "Change textures and shaders.",
        "settings.shortcuts.title": "Keybinds",
        "settings.shortcuts.desc": "Customize controls.",
        "settings.shortcuts.global": "Movement & Admin",
        "settings.shortcuts.flashcards": "Combat",
        "settings.theme.light": "Overworld (Day)",
        "settings.theme.dark": "The End (Night)",
        "settings.theme.system": "Redstone Lamp",
        "settings.save.button": "Save to Chunk",
        "settings.save.saving": "Saving Level...",
        "settings.save.success": "Level.dat saved!",
        "settings.save.error": "Corrupted Chunk!",
        "settings.api.perplexity.default": "Default Server",
        "settings.api.perplexity.summaries": "Librarian Trade",
        "settings.api.perplexity.exercises": "Combat Training",
        "settings.api.gemini.vincent": "Vincent's Server",
        "settings.api.gemini.summaries": "Gemini Trade",
        "settings.api.gemini.exercises": "Gemini Quest",
        "settings.api.integrations": "Mod Integrations",
        "settings.api.calendar": "Daylight Cycle",
        // Generation Menu
        "gen.menu.button": "Spawn Logic",
        "gen.menu.title": "Spawn Mobs/Items",
        "gen.flashcards.title": "Mob Spawner",
        "gen.flashcards.desc": "Spawn entities for XP farming.",
        "gen.quiz.title": "Dungeon Trial",
        "gen.quiz.desc": "Test your survival skills.",
        "gen.plan.title": "Adventure Map",
        "gen.plan.desc": "Generate a quest path.",
        "gen.viewAll": "Open Quest Log",
        "gen.empty": "Mob cap reached (Empty)",
        "gen.start": "Use Spawner Egg",
        "gen.list.cards": "mobs",
        "gen.list.questions": "challenges",
        "gen.list.mastery": "XP Level",
        "gen.action.start": "Enter Dungeon",
        "gen.action.quiz": "Accept Challenge",
        "gen.delete.confirm": "Despawn this entity?",
        "gen.delete.error": "Chunk error!",
        "common.open": "Teleport",
        "common.in": "in",

        // TTS (MC)
        "tts.play": "Activate Voice Crystal",
        "tts.pause": "Mute Crystal",
        "tts.resume": "Unmute Crystal",
        "tts.stop": "Shatter Crystal",
        "tts.speed": "Enchantment Level",
        "tts.unsupported": "Voice Crystal not found in inventory",
        "tts.error": "Crystal malfunction",
        "tts.reading": "Crystal speaking...",

        // STT (MC)
        "stt.start": "Cast Whisper Spell",
        "stt.stop": "Silence Spell",
        "stt.listening": "Spirits are listening...",
        "stt.unsupported": "No magic detected",

        // Item Edit
        "item.edit": "Enchant Item",
        "item.edit.title": "Enchant Loot",
        "item.edit.replaceFile": "Swap Item",
        "item.edit.keepFile": "Keep Current Drop",
        "item.edit.success": "Item enchanted successfully",
        "sort.label": "Order:",
        "sort.dateAdded": "Spawn Time",
        "sort.alphabetical": "A-Z Scrolls",
        "sort.lastOpened": "Last Traveled",
        "grid.columns": "Chunks",
        "bulk.selected_singular": "Entity selected",
        "bulk.selected_plural": "Entities selected",
        "bulk.generate": "Spawn Logic",
        "bulk.generate.flashcards": "Mob Spawner",
        "bulk.generate.quiz": "Dungeon Trial",
        "bulk.generate.summary": "Enchanted Scroll",
        "action.selectAll": "Select All Chunks",
        "changelog.v051.title": "Mobility & Stability 📱⚡",
        "changelog.v051.mobile": "Pocket UI: Reworked Course View with compact stacks and Beacon-powered intelligent headers.",
        "changelog.v051.folders": "Open Portals: Biomes are now open by default and dungeon navigation is smoother.",
        "changelog.v051.office": "Hybrid Scrolls: Integrated Google Scrolls for reading PPT/Excel enchantments.",
        "changelog.v051.api": "Redstone Logic: Fixed server-side lag, API drops, and chunk loading errors.",
        "changelog.v051.polish": "Texture Pack: 100% lore translation, fixed void-blur on modals, and optimized inventory list view.",
        "changelog.v052.title": "Productivity & Quests 🚀",
        "changelog.v052.revision": "AI Quest Planner: Forge a personalized grind path with Enchanting Table.",
        "changelog.v052.edit": "Item Enchanting: Modify dropped loot and swap items without respawning.",
        "changelog.v052.vscode": "Redstone IDE: Teleport to VS Code from your inventory.",
        "changelog.v052.pptx": "Ancient Scrolls: Read PPTX/DOCX via Google/Microsoft portals.",
        "changelog.v052.ui": "Block Fixes: Centered menus, smoother borders.",
        "changelog.v053.title": "Chunk Loading & FPS ⚡",
        "changelog.v053.perf": "FPS Boost: Frame rate increased from 53 to 90+.",
        "changelog.v053.cache": "Chunk Caching: Chunks are saved to disk for instant loading.",
        "changelog.v053.lazy": "Render Distance: Far chunks load only when needed.",
        "changelog.v053.images": "Texture Optimization: Textures are compressed to save VRAM.",

        // v0.5.4
        "changelog.v054.title": "Redstone Update",
        "changelog.v054.board": "Added Conspiracy Map.",
        "changelog.v054.command": "Added Command Block Center.",
        "changelog.v054.focus": "Added Day/Night Cycle Timer.",
        "changelog.v054.sidebar": "Piston-powered Menu.",

        // v0.5.9
        "changelog.v059.title": "Focus & Shaders 🎨",
        "changelog.v059.analytics": "Beacon Stats: Logging your mining sessions with enchanted charts.",
        "changelog.v059.themes": "Resource Packs: New 'Nature' and 'Sunset' textures for your interface.",
        "changelog.v059.dashboard": "Daylight Mode: Dashboard now supports Overworld (Day) theme.",
        "changelog.v059.notes": "Book Styling: Standardized book layouts to match the Scribe's Desk.",

        // Revision Program (Minecraft)
        "revision.program": "Quest Planner",
        "revision.generate": "Forge Quest Path",
        "revision.selectTarget": "Select Dungeon or Biome",
        "revision.examDate": "Boss Battle Date",
        "revision.noCalendar": "No calendar scroll found",
        "revision.linkCalendar": "Bind a Calendar",
        "revision.availableTime": "Grind Time Available",
        "revision.hours": "Hours",
        "revision.days": "Days",
        "revision.generating": "The ancient ones are crafting your path...",
        // Auth (Minecraft)
        "auth.welcome.back": "Welcome back, Steve",
        "auth.create.account": "Spawn New Player",
        "auth.login.desc": "Login to the Server",
        "auth.register.desc": "Whitelist Request",
        "auth.name": "Gamertag",
        "auth.email": "Redstone Signal (Email)",
        "auth.password": "Server PC",
        "auth.submit.login": "Join Server",
        "auth.submit.register": "Spawn In",
        "auth.switch.toRegister": "No whitelist? Request Access",
        "auth.switch.toLogin": "Already whitelisted? Join",
        "auth.error.default": "Kicked from server: Auth Failed",
        "auth.error.missing": "Missing Command Arguments",

        // v0.5.5
        "changelog.v055.title": "Map Table - Full Release",
        "changelog.v055.board_complete": "Phase 3: Search, advanced filters, and mini-map added.",
        "changelog.v055.drag_drop": "Drag & Drop: Assign orphan courses to topics via dragging.",
        "changelog.v055.filters": "Advanced Filters (Topics, Courses) for better navigation.",
        "changelog.v055.layout": "Improved radial layout algorithm and node positioning.",
        // v0.5.6
        "changelog.v056.title": "Item Integration",
        "changelog.v056.documents": "Documents (PDF, Images, Office) now spawn on the Map Table.",
        "changelog.v056.filters": "Added Documents filter to show/hide items.",
        // v0.5.7
        "changelog.v057.title": "Visual Upgrades",
        "changelog.v057.cork": "Improved cork board texture (CSS pattern instead of external resource).",
        "changelog.v057.pins": "Added colored pins to all nodes (Red: Topics, Yellow: Courses, Blue: Items).",
        "changelog.v057.documents_fix": "Fixed document filter rendering bug.",
        "changelog.v057.reset_view": "Reset view now centers smartly on existing content.",
        // v0.5.0
        "changelog.v050.title": "Stability & Intelligence 🧠",
        "changelog.v050.api_keys": "Saving Level.dat: Fixed a bug where world keys were lost.",
        "changelog.v050.logout": "Safe Quit: The 'Quit' button now properly saves your player state.",
        "changelog.v050.ai_reliability": "Reliable NPCs: Fixed Villager trade errors and Gemini quota management.",
        "changelog.v050.polish": "Texture Pack: Polished English labels and Minecraft mode everywhere.",
        "changelog.v041.title": "Loot Hub 📂",
        "changelog.v041.viewer": "Omni-Lens: Native support for PDF scrolls, Books and Maps.",
        "changelog.v041.metadata": "NBT Tags: Clearer loot cards showing durability and enchants.",
        "changelog.v041.delete_fix": "TNT Deletion: Fixed 'Block not found' errors.",
        "changelog.v041.doc_type": "Item Sorting: Enhanced item detection system.",
        "changelog.v040.title": "Realm Sync 🔄",
        "changelog.v040.infra": "Multiplayer Backend: Reworked the synchronization core.",
        "changelog.v040.upload": "Item Drop: Fixed item pickup failures.",
        "changelog.v040.schema": "World Gen: Fixed UUID generation for chunks and biomes.",
        "changelog.v040.speed": "Tick Rate: Reduced sync delay for instant interaction.",
        "changelog.v030.title": "Beacon & Shaders 🌍",
        "changelog.v030.focus": "Beacon Mode: Scribe summaries without distraction from Creepers.",
        "changelog.v030.multilang": "Villager Trades: Multi-language support added (including Minecraftian!).",
        "changelog.v030.ai2": "Redstone Logic 2.0: Improved AI scrolls for better loot data.",
        "changelog.v030.export": "Scroll Export: Download your books as .pdf and .docx loot.",
        "changelog.v020.title": "Scroll Export & Locate",
        "changelog.v020.pdf": "Professional Scrolls: Enchanted PDF generation.",
        "changelog.v020.command": "Cheat Code: `Cmd+K` to locate any block instantly.",
        "changelog.v020.analytics": "Server Stats: See your activity timeline.",
        "changelog.v020.large_files": "Bedrock Optimization: Smooth handling of massive schematics.",
        "changelog.v015.title": "Chunks & Organisation",
        "changelog.v015.recursive": "Infinite Biomes: Recursive folder structure.",
        "changelog.v015.favorites": "Hotbar: Pin your most expensive loot for quick access.",
        "changelog.v015.dnd": "Inventory Sort: Drag & drop items to reorder chunks.",
        "changelog.v010.title": "The Big Bang",
        "changelog.v010.engine": "Game Engine: Worlds, Books, Quests.",
        "changelog.v010.graph": "Map Room: Visualized knowledge graph.",
        "changelog.current": "LIVE",
        // Mind Maps
        "mindmap": "Mind Map",
        "nav.mindmaps": "Realm Maps",

        "mindmap.title": "Map Room",
        "mindmap.subtitle": "Cartography of your knowledge base.",
        "mindmap.new": "Craft Map",
        "mindmap.search": "Locate map...",
        "mindmap.empty.title": "No maps crafted",
        "mindmap.empty.desc": "Combine Paper and Compass to create your first map.",
        "mindmap.empty.action": "Craft Map",
        "mindmap.sources": "biomes",
        "mindmap.open": "View Map",
        "mindmap.delete.confirm": "Throw this map into lava?",
        // Generation Modal
        "mindmap.gen.title": "Enchant Map",
        "mindmap.gen.name": "Map Name (Optional)",
        "mindmap.gen.name.placeholder": "e.g. Stronghold Coordinates",
        "mindmap.gen.notes.label": "Select Books to Enchant",
        "mindmap.gen.notes.placeholder": "Locate written books...",
        "mindmap.gen.file.label": "Select Scrolls to Analyze",
        "mindmap.gen.file.placeholder": "Locate scrolls...",
        "mindmap.gen.doc.selected": "Selected Scroll",
        "mindmap.gen.upload.label": "Drop Item Stack (Soon)",
        "mindmap.gen.cancel": "Sneak",
        "mindmap.gen.submit": "Enchant",
        "mindmap.gen.generating": "Rendering chunks...",
        "mindmap.gen.success": "Map crafted!",
        "mindmap.gen.error": "Crafting failed!",
        "ai.model.label": "Select Enchantment Source"
    },
}


type LanguageProviderProps = {
    children: React.ReactNode
    defaultLanguage?: Language
    storageKey?: string
}

type LanguageProviderState = {
    language: Language
    setLanguage: (language: Language) => void
    t: (key: string, variables?: Record<string, string | number>) => string
}

const initialState: LanguageProviderState = {
    language: "fr",
    setLanguage: () => null,
    t: (key) => key,
}

const LanguageProviderContext = createContext<LanguageProviderState>(initialState)

export function LanguageProvider({
    children,
    defaultLanguage = "fr",
    storageKey = "vite-ui-language",
    ...props
}: LanguageProviderProps) {
    const [language, setLanguage] = useState<Language>(
        () => (localStorage.getItem(storageKey) as Language) || defaultLanguage
    )

    useEffect(() => {
        localStorage.setItem(storageKey, language)

        // Global Theme Injection for Minecraft Mode
        if (language === 'mc') {
            document.body.classList.add('minecraft-theme')
        } else {
            document.body.classList.remove('minecraft-theme')
        }
    }, [language, storageKey])

    const t = (key: string, variables?: Record<string, string | number>) => {
        let text = translations[language][key] || key
        if (variables) {
            Object.entries(variables).forEach(([k, v]) => {
                text = text.replace(`{${k}}`, String(v))
            })
        }
        return text
    }

    const value = {
        language,
        setLanguage,
        t
    }

    return (
        <LanguageProviderContext.Provider value={value} {...props}>
            {children}
        </LanguageProviderContext.Provider>
    )
}

export const useLanguage = () => {
    const context = useContext(LanguageProviderContext)

    if (context === undefined)
        throw new Error("useLanguage must be used within a LanguageProvider")

    return context
}
